// ================================================================
// Portal Form Definitions — Verified Government Application Form Schemas
// Includes multi-step structures, field types, and confusing question guides
// ================================================================

import type { PortalFormSchema } from './types';

export const NSP_SCHOLARSHIP_FORM: PortalFormSchema = {
  portalId: 'nsp',
  formId: 'nsp_fresh_application_2026',
  title: 'National Scholarship Portal — Fresh Application (2026-27)',
  titleHi: 'राष्ट्रीय छात्रवृत्ति पोर्टल — नवीन आवेदन (2026-27)',
  totalSteps: 4,
  stepTitles: [
    '1. Registration & Personal Details',
    '2. Academic & Scheme Eligibility',
    '3. Upload Required Certificates',
    '4. Security Verification & Review',
  ],
  requiresOtp: true,
  requiresCaptcha: true,
  requiresPayment: false,
  fields: [
    // ── STEP 1: Personal Details ─────────────────────────────
    {
      id: 'nsp_full_name',
      name: 'applicantName',
      label: 'Applicant Full Name',
      labelHi: 'आवेदक का पूरा नाम',
      type: 'text',
      required: true,
      section: 'Personal Details',
      sectionHi: 'व्यक्तिगत विवरण',
      stepNumber: 1,
      placeholder: 'As per Aadhaar Card',
    },
    {
      id: 'nsp_dob',
      name: 'dateOfBirth',
      label: 'Date of Birth (DOB)',
      labelHi: 'जन्म तिथि',
      type: 'date',
      required: true,
      section: 'Personal Details',
      sectionHi: 'व्यक्तिगत विवरण',
      stepNumber: 1,
    },
    {
      id: 'nsp_gender',
      name: 'gender',
      label: 'Gender',
      labelHi: 'लिंग',
      type: 'select',
      required: true,
      section: 'Personal Details',
      sectionHi: 'व्यक्तिगत विवरण',
      stepNumber: 1,
      options: [
        { value: 'male', label: 'Male', labelHi: 'पुरुष' },
        { value: 'female', label: 'Female', labelHi: 'महिला' },
        { value: 'other', label: 'Other', labelHi: 'अन्य' },
      ],
    },
    {
      id: 'nsp_state',
      name: 'stateOfDomicile',
      label: 'State of Domicile',
      labelHi: 'मूल निवास राज्य',
      type: 'select',
      required: true,
      section: 'Address Details',
      sectionHi: 'पते का विवरण',
      stepNumber: 1,
      options: [
        { value: 'Punjab', label: 'Punjab', labelHi: 'पंजाब' },
        { value: 'Haryana', label: 'Haryana', labelHi: 'हरियाणा' },
        { value: 'Rajasthan', label: 'Rajasthan', labelHi: 'राजस्थान' },
        { value: 'Uttar Pradesh', label: 'Uttar Pradesh', labelHi: 'उत्तर प्रदेश' },
        { value: 'Bihar', label: 'Bihar', labelHi: 'बिहार' },
        { value: 'Delhi', label: 'Delhi', labelHi: 'दिल्ली' },
      ],
    },
    {
      id: 'nsp_district',
      name: 'district',
      label: 'District',
      labelHi: 'ज़िला',
      type: 'select',
      required: true,
      section: 'Address Details',
      sectionHi: 'पते का विवरण',
      stepNumber: 1,
      options: [
        { value: 'Ludhiana', label: 'Ludhiana', labelHi: 'लुधियाना' },
        { value: 'Amritsar', label: 'Amritsar', labelHi: 'अमृतसर' },
        { value: 'Patiala', label: 'Patiala', labelHi: 'पटियाला' },
        { value: 'Jalandhar', label: 'Jalandhar', labelHi: 'जालंधर' },
        { value: 'Jaipur', label: 'Jaipur', labelHi: 'जयपुर' },
        { value: 'Patna', label: 'Patna', labelHi: 'पटना' },
        { value: 'Lucknow', label: 'Lucknow', labelHi: 'लखनऊ' },
      ],
    },
    {
      id: 'nsp_pincode',
      name: 'pinCode',
      label: 'Postal PIN Code',
      labelHi: 'पिन कोड',
      type: 'number',
      required: true,
      section: 'Address Details',
      sectionHi: 'पते का विवरण',
      stepNumber: 1,
      placeholder: '6-digit PIN code',
    },
    {
      id: 'nsp_mobile',
      name: 'mobileNumber',
      label: 'Mobile Number',
      labelHi: 'मोबाइल नंबर',
      type: 'number',
      required: true,
      section: 'Contact Details',
      sectionHi: 'संपर्क विवरण',
      stepNumber: 1,
      placeholder: '10-digit mobile number',
    },
    {
      id: 'nsp_email',
      name: 'emailAddress',
      label: 'Email ID',
      labelHi: 'ईमेल आईडी',
      type: 'text',
      required: false,
      section: 'Contact Details',
      sectionHi: 'संपर्क विवरण',
      stepNumber: 1,
      placeholder: 'example@gmail.com',
    },

    // ── STEP 2: Academic & Eligibility ───────────────────────
    {
      id: 'nsp_category',
      name: 'communityCategory',
      label: 'Social Category / Community',
      labelHi: 'सामाजिक श्रेणी / वर्ग',
      type: 'select',
      required: true,
      section: 'Academic & Eligibility',
      sectionHi: 'शैक्षणिक एवं पात्रता',
      stepNumber: 2,
      options: [
        { value: 'General', label: 'General / Open', labelHi: 'सामान्य' },
        { value: 'OBC', label: 'OBC (Other Backward Classes)', labelHi: 'अन्य पिछड़ा वर्ग (OBC)' },
        { value: 'SC', label: 'SC (Scheduled Caste)', labelHi: 'अनुसूचित जाति (SC)' },
        { value: 'ST', label: 'ST (Scheduled Tribe)', labelHi: 'अनुसूचित जनजाति (ST)' },
        { value: 'EWS', label: 'EWS (Economically Weaker Section)', labelHi: 'आर्थिक रूप से कमजोर वर्ग (EWS)' },
      ],
    },
    {
      id: 'nsp_annual_income',
      name: 'annualFamilyIncome',
      label: 'Annual Family Income (₹)',
      labelHi: 'वार्षिक पारिवारिक आय (₹)',
      type: 'number',
      required: true,
      section: 'Academic & Eligibility',
      sectionHi: 'शैक्षणिक एवं पात्रता',
      stepNumber: 2,
      placeholder: 'As per Income Certificate (e.g. 85000)',
    },
    {
      id: 'nsp_institution',
      name: 'institutionName',
      label: 'Institution / College / School Name',
      labelHi: 'संस्थान / कॉलेज / स्कूल का नाम',
      type: 'text',
      required: true,
      section: 'Academic & Eligibility',
      sectionHi: 'शैक्षणिक एवं पात्रता',
      stepNumber: 2,
      placeholder: 'e.g. Government Polytechnic College',
    },
    {
      id: 'nsp_course',
      name: 'presentClassCourse',
      label: 'Present Course / Degree',
      labelHi: 'वर्तमान पाठ्यक्रम / डिग्री',
      type: 'text',
      required: true,
      section: 'Academic & Eligibility',
      sectionHi: 'शैक्षणिक एवं पात्रता',
      stepNumber: 2,
      placeholder: 'e.g. B.Tech Computer Science, Class 12, etc.',
    },
    {
      id: 'nsp_day_scholar',
      name: 'dayScholarHosteller',
      label: 'Day Scholar / Hosteller',
      labelHi: 'डे स्कॉलर / हॉस्टलर',
      type: 'select',
      required: true,
      section: 'Academic & Eligibility',
      sectionHi: 'शैक्षणिक एवं पात्रता',
      stepNumber: 2,
      options: [
        { value: 'day_scholar', label: 'Day Scholar (Lives at home)', labelHi: 'डे स्कॉलर (घर से कॉलेज जाते हैं)' },
        { value: 'hosteller', label: 'Hosteller (Lives in college hostel / PG)', labelHi: 'हॉस्टलर (हॉस्टल या पीजी में रहते हैं)' },
      ],
      explanation: {
        questionTitle: 'Day Scholar vs Hosteller',
        en: 'This asks where you live during your studies. "Day Scholar" means you commute from home. "Hosteller" means you reside in an institutional hostel or paid PG.',
        hi: 'यह पूछता है कि आप पढ़ाई के दौरान कहाँ रहते हैं। "डे स्कॉलर" का मतलब है कि आप घर से आते-जाते हैं। "हॉस्टलर" का मतलब है कि आप कॉलेज हॉस्टल या किराये के कमरे में रहते हैं।',
        suggestedOptions: [
          { label: 'घर से जाते हैं (Day Scholar)', value: 'day_scholar' },
          { label: 'हॉस्टल में रहते हैं (Hosteller)', value: 'hosteller' },
        ],
      },
    },
    {
      id: 'nsp_ward_ex_serviceman',
      name: 'wardOfExServiceman',
      label: 'Are you a ward of an ex-serviceman?',
      labelHi: 'क्या आप पूर्व सैनिक के आश्रित (Ward of Ex-Serviceman) हैं?',
      type: 'radio',
      required: true,
      section: 'Academic & Eligibility',
      sectionHi: 'शैक्षणिक एवं पात्रता',
      stepNumber: 2,
      options: [
        { value: 'no', label: 'No', labelHi: 'नहीं' },
        { value: 'yes', label: 'Yes', labelHi: 'हाँ' },
      ],
      explanation: {
        questionTitle: 'Ward of Ex-Serviceman',
        en: 'This asks whether you are the child or dependent of a former member of the Indian Armed Forces (Army, Navy, Air Force). If none of your parents served, choose No.',
        hi: 'यह पूछता है कि क्या आपके माता-पिता में से कोई भारतीय सेना (Army, Navy, Air Force) में पूर्व सैनिक रहे हैं। अगर नहीं, तो "नहीं" चुनें।',
        suggestedOptions: [
          { label: 'नहीं (No)', value: 'no' },
          { label: 'हाँ (Yes)', value: 'yes' },
        ],
      },
    },

    // ── STEP 3: Upload Documents ─────────────────────────────
    {
      id: 'nsp_doc_income',
      name: 'incomeCertificateDoc',
      label: 'Income Certificate',
      labelHi: 'आय प्रमाण पत्र (Income Certificate)',
      type: 'file',
      required: true,
      section: 'Document Uploads',
      sectionHi: 'दस्तावेज़ अपलोड',
      stepNumber: 3,
    },
    {
      id: 'nsp_doc_caste',
      name: 'casteCertificateDoc',
      label: 'Caste Certificate (SC/ST/OBC)',
      labelHi: 'जाति प्रमाण पत्र (Caste Certificate)',
      type: 'file',
      required: false,
      section: 'Document Uploads',
      sectionHi: 'दस्तावेज़ अपलोड',
      stepNumber: 3,
    },
    {
      id: 'nsp_doc_marksheet',
      name: 'previousMarksheetDoc',
      label: 'Previous Year Marksheet',
      labelHi: 'पिछली कक्षा की अंकतालिका (Marksheet)',
      type: 'file',
      required: true,
      section: 'Document Uploads',
      sectionHi: 'दस्तावेज़ अपलोड',
      stepNumber: 3,
    },
    {
      id: 'nsp_doc_residence',
      name: 'domicileCertificateDoc',
      label: 'Domicile / Residence Certificate',
      labelHi: 'मूल निवास प्रमाण पत्र (Domicile Certificate)',
      type: 'file',
      required: false,
      section: 'Document Uploads',
      sectionHi: 'दस्तावेज़ अपलोड',
      stepNumber: 3,
    },

    // ── STEP 4: Bank, Review & Security Verification ─────────
    {
      id: 'nsp_bank_account',
      name: 'bankAccountNumber',
      label: 'Bank Account Number',
      labelHi: 'बैंक खाता संख्या',
      type: 'text',
      required: true,
      isSensitive: true,
      section: 'Bank & Security Verification',
      sectionHi: 'बैंक एवं सुरक्षा सत्यापन',
      stepNumber: 4,
      placeholder: 'Aadhaar-seeded bank account',
    },
    {
      id: 'nsp_ifsc_code',
      name: 'ifscCode',
      label: 'Bank IFSC Code',
      labelHi: 'बैंक IFSC कोड',
      type: 'text',
      required: true,
      section: 'Bank & Security Verification',
      sectionHi: 'बैंक एवं सुरक्षा सत्यापन',
      stepNumber: 4,
      placeholder: 'e.g. SBIN0001234',
    },
    {
      id: 'nsp_captcha',
      name: 'captchaText',
      label: 'Security CAPTCHA',
      labelHi: 'सुरक्षा कैप्चा (CAPTCHA)',
      type: 'captcha',
      required: true,
      section: 'Bank & Security Verification',
      sectionHi: 'बैंक एवं सुरक्षा सत्यापन',
      stepNumber: 4,
      placeholder: 'Enter letters shown in image',
    },
    {
      id: 'nsp_otp',
      name: 'aadhaarOtp',
      label: 'Aadhaar Mobile OTP',
      labelHi: 'आधार मोबाइल ओटीपी',
      type: 'otp',
      required: true,
      isSensitive: true,
      section: 'Bank & Security Verification',
      sectionHi: 'बैंक एवं सुरक्षा सत्यापन',
      stepNumber: 4,
      placeholder: '6-digit OTP received on mobile',
    },
  ],
};

export const PM_KISAN_FORM: PortalFormSchema = {
  portalId: 'pm-kisan',
  formId: 'pm_kisan_registration_2026',
  title: 'PM-KISAN Samman Nidhi — New Farmer Registration',
  titleHi: 'पीएम-किसान सम्मान निधि — नवीन किसान पंजीकरण',
  totalSteps: 3,
  stepTitles: [
    '1. Rural Farmer & Location Details',
    '2. Landholding Records (Khata / Khasra)',
    '3. Aadhaar Verification & eKYC',
  ],
  requiresOtp: true,
  requiresCaptcha: true,
  requiresPayment: false,
  fields: [
    {
      id: 'pmk_state',
      name: 'state',
      label: 'State',
      labelHi: 'राज्य',
      type: 'select',
      required: true,
      section: 'Farmer Location',
      stepNumber: 1,
      options: [
        { value: 'Punjab', label: 'Punjab' },
        { value: 'Haryana', label: 'Haryana' },
        { value: 'Rajasthan', label: 'Rajasthan' },
        { value: 'Uttar Pradesh', label: 'Uttar Pradesh' },
      ],
    },
    {
      id: 'pmk_district',
      name: 'district',
      label: 'District',
      labelHi: 'ज़िला',
      type: 'select',
      required: true,
      section: 'Farmer Location',
      stepNumber: 1,
      options: [
        { value: 'Ludhiana', label: 'Ludhiana' },
        { value: 'Patiala', label: 'Patiala' },
        { value: 'Jaipur', label: 'Jaipur' },
      ],
    },
    {
      id: 'pmk_sub_district',
      name: 'subDistrict',
      label: 'Sub-District / Tehsil',
      labelHi: 'उप-ज़िला / तहसील',
      type: 'text',
      required: true,
      section: 'Farmer Location',
      stepNumber: 1,
    },
    {
      id: 'pmk_village',
      name: 'village',
      label: 'Village',
      labelHi: 'गाँव',
      type: 'text',
      required: true,
      section: 'Farmer Location',
      stepNumber: 1,
    },
    {
      id: 'pmk_farmer_name',
      name: 'farmerName',
      label: 'Farmer Full Name',
      labelHi: 'किसान का पूरा नाम',
      type: 'text',
      required: true,
      section: 'Farmer Identity',
      stepNumber: 1,
    },
    {
      id: 'pmk_gender',
      name: 'gender',
      label: 'Gender',
      labelHi: 'लिंग',
      type: 'select',
      required: true,
      section: 'Farmer Identity',
      stepNumber: 1,
      options: [
        { value: 'male', label: 'Male' },
        { value: 'female', label: 'Female' },
      ],
    },
    {
      id: 'pmk_category',
      name: 'category',
      label: 'Farmer Category',
      labelHi: 'किसान श्रेणी',
      type: 'select',
      required: true,
      section: 'Farmer Identity',
      stepNumber: 1,
      options: [
        { value: 'General', label: 'General / Others' },
        { value: 'SC', label: 'SC' },
        { value: 'ST', label: 'ST' },
      ],
    },
    {
      id: 'pmk_farmer_type',
      name: 'farmerType',
      label: 'Farmer Holding Type',
      labelHi: 'किसान जोत प्रकार',
      type: 'select',
      required: true,
      section: 'Farmer Identity',
      stepNumber: 1,
      options: [
        { value: 'small_marginal', label: 'Small & Marginal (1-2 Hectares)' },
        { value: 'other', label: 'Others (> 2 Hectares)' },
      ],
    },
    // Step 2: Land Records
    {
      id: 'pmk_land_details',
      name: 'landKhataNumber',
      label: 'Land Holding Khata / Khasra No.',
      labelHi: 'भूमि खता / खसरा संख्या',
      type: 'text',
      required: true,
      section: 'Land Records',
      stepNumber: 2,
    },
    {
      id: 'pmk_doc_land',
      name: 'landRecordDoc',
      label: 'Land Revenue Record (Jamabandi / Fard)',
      labelHi: 'जमाबंदी / फर्द दस्तावेज़',
      type: 'file',
      required: true,
      section: 'Land Records',
      stepNumber: 2,
    },
    // Step 3: Security & OTP
    {
      id: 'pmk_aadhaar',
      name: 'aadhaarNumber',
      label: 'Aadhaar Number',
      labelHi: 'आधार संख्या',
      type: 'text',
      required: true,
      isSensitive: true,
      section: 'eKYC Verification',
      stepNumber: 3,
    },
    {
      id: 'pmk_captcha',
      name: 'captcha',
      label: 'Security CAPTCHA',
      labelHi: 'कैप्चा',
      type: 'captcha',
      required: true,
      section: 'eKYC Verification',
      stepNumber: 3,
    },
    {
      id: 'pmk_otp',
      name: 'otp',
      label: 'Aadhaar OTP',
      labelHi: 'आधार ओटीपी',
      type: 'otp',
      required: true,
      isSensitive: true,
      section: 'eKYC Verification',
      stepNumber: 3,
    },
  ],
};

export const PORTAL_FORM_REGISTRY: Record<string, PortalFormSchema> = {
  nsp: NSP_SCHOLARSHIP_FORM,
  'pm-kisan': PM_KISAN_FORM,
};

export function getFormSchemaForPortal(portalId: string): PortalFormSchema {
  return PORTAL_FORM_REGISTRY[portalId] || NSP_SCHOLARSHIP_FORM;
}
