// ============================================================
// UPAg Domestic Crop Calendar — Reference Dataset
// Source: Government of India UPAg / ICAR & Indian Horticulture Database (2014)
// URL: https://upag.gov.in/national-calendar
// ============================================================

export type CropPhase = 'sowing' | 'growing' | 'harvesting' | 'off';

export interface MonthPhaseDetail {
  month: number; // 1 = Jan, 12 = Dec
  monthName: string;
  phase: CropPhase;
  timing?: string; // 'Early' | 'Middle' | 'Late' | 'Beginning' | 'Beginning to Middle' | 'Middle to End'
  timingCode?: string; // 'E' | 'M' | 'L' | 'B' | 'B-M' | 'M-E'
}

export interface UPAgCropRecord {
  id: string;
  state: string;
  season: 'Kharif' | 'Rabi' | 'Zaid / Summer' | 'Annual';
  crop: string;
  localName: string; // Hindi / local script name
  primaryCategory: 'Foodgrain' | 'Oilseeds' | 'Pulses' | 'Commercial' | 'Horticulture' | 'Fibre';
  sowingWindow: string;
  growingWindow: string;
  harvestingWindow: string;
  months: Record<number, MonthPhaseDetail>;
  source: string;
}

export const MONTH_NAMES = [
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December',
];

export const MONTH_NAMES_HI = [
  'जनवरी',
  'फरवरी',
  'मार्च',
  'अप्रैल',
  'मई',
  'जून',
  'जुलाई',
  'अगस्त',
  'सितंबर',
  'अक्टूबर',
  'नवंबर',
  'दिसंबर',
];

export const OFFICIAL_INDIAN_STATES = [
  { id: 'rajasthan', name: 'Rajasthan', nameHi: 'राजस्थान' },
  { id: 'punjab', name: 'Punjab', nameHi: 'पंजाब' },
  { id: 'haryana', name: 'Haryana', nameHi: 'हरियाणा' },
  { id: 'uttar-pradesh', name: 'Uttar Pradesh', nameHi: 'उत्तर प्रदेश' },
  { id: 'madhya-pradesh', name: 'Madhya Pradesh', nameHi: 'मध्य प्रदेश' },
  { id: 'gujarat', name: 'Gujarat', nameHi: 'गुजरात' },
  { id: 'maharashtra', name: 'Maharashtra', nameHi: 'महाराष्ट्र' },
  { id: 'bihar', name: 'Bihar', nameHi: 'बिहार' },
  { id: 'karnataka', name: 'Karnataka', nameHi: 'कर्नाटक' },
  { id: 'tamil-nadu', name: 'Tamil Nadu', nameHi: 'तमिलनाडु' },
  { id: 'andhra-pradesh', name: 'Andhra Pradesh', nameHi: 'आंध्र प्रदेश' },
  { id: 'telangana', name: 'Telangana', nameHi: 'तेलंगाना' },
  { id: 'west-bengal', name: 'West Bengal', nameHi: 'पश्चिम बंगाल' },
  { id: 'odisha', name: 'Odisha', nameHi: 'ओडिशा' },
  { id: 'assam', name: 'Assam', nameHi: 'असम' },
  { id: 'chhattisgarh', name: 'Chhattisgarh', nameHi: 'छत्तीसगढ़' },
  { id: 'jharkhand', name: 'Jharkhand', nameHi: 'झारखंड' },
  { id: 'himachal-pradesh', name: 'Himachal Pradesh', nameHi: 'हिमाचल प्रदेश' },
  { id: 'jammu-kashmir', name: 'Jammu & Kashmir', nameHi: 'जम्मू और कश्मीर' },
  { id: 'uttarakhand', name: 'Uttarakhand', nameHi: 'उत्तराखंड' },
  { id: 'kerala', name: 'Kerala', nameHi: 'केरल' },
  { id: 'all-india', name: 'All India', nameHi: 'अखिल भारतीय' },
];

function createMonthMap(specs: {
  sowing: { months: number[]; timing?: Record<number, string> };
  growing: { months: number[] };
  harvesting: { months: number[]; timing?: Record<number, string> };
}): Record<number, MonthPhaseDetail> {
  const map: Record<number, MonthPhaseDetail> = {};

  for (let m = 1; m <= 12; m++) {
    const monthName = MONTH_NAMES[m - 1];
    let phase: CropPhase = 'off';
    let timing: string | undefined;
    let timingCode: string | undefined;

    if (specs.sowing.months.includes(m)) {
      phase = 'sowing';
      timing = specs.sowing.timing?.[m] || 'Normal';
    } else if (specs.harvesting.months.includes(m)) {
      phase = 'harvesting';
      timing = specs.harvesting.timing?.[m] || 'Normal';
    } else if (specs.growing.months.includes(m)) {
      phase = 'growing';
    }

    if (timing) {
      if (timing.toLowerCase().includes('early')) timingCode = 'E';
      else if (timing.toLowerCase().includes('middle')) timingCode = 'M';
      else if (timing.toLowerCase().includes('late')) timingCode = 'L';
      else if (timing.toLowerCase().includes('beginning')) timingCode = 'B';
    }

    map[m] = {
      month: m,
      monthName,
      phase,
      timing,
      timingCode,
    };
  }

  return map;
}

// ────────────────────────────────────────────────────────────
// Official Domestic Crop Calendar Records (UPAg / ICAR - 2014)
// ────────────────────────────────────────────────────────────

export const UPAG_DOMESTIC_CROP_CALENDAR: UPAgCropRecord[] = [
  // ==================== RAJASTHAN ====================
  {
    id: 'raj-bajra',
    state: 'Rajasthan',
    season: 'Kharif',
    crop: 'Bajra (Pearl Millet)',
    localName: 'बाजरा',
    primaryCategory: 'Foodgrain',
    sowingWindow: 'June (Late) – July (Late)',
    growingWindow: 'August',
    harvestingWindow: 'September (Middle) – October (Beginning)',
    months: createMonthMap({
      sowing: { months: [6, 7], timing: { 6: 'Late', 7: 'Early to Middle' } },
      growing: { months: [8] },
      harvesting: { months: [9, 10], timing: { 9: 'Middle to Late', 10: 'Beginning' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'raj-wheat',
    state: 'Rajasthan',
    season: 'Rabi',
    crop: 'Wheat',
    localName: 'गेहूं',
    primaryCategory: 'Foodgrain',
    sowingWindow: 'October (Late) – December (Beginning)',
    growingWindow: 'January – February',
    harvestingWindow: 'March (Middle) – April (Late)',
    months: createMonthMap({
      sowing: { months: [10, 11, 12], timing: { 10: 'Late', 11: 'Middle', 12: 'Beginning' } },
      growing: { months: [1, 2] },
      harvesting: { months: [3, 4], timing: { 3: 'Middle', 4: 'Early to Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'raj-mustard',
    state: 'Rajasthan',
    season: 'Rabi',
    crop: 'Mustard (Sarson / Rai)',
    localName: 'सरसों',
    primaryCategory: 'Oilseeds',
    sowingWindow: 'September (Late) – November (Early)',
    growingWindow: 'December – January',
    harvestingWindow: 'February (Middle) – March (Late)',
    months: createMonthMap({
      sowing: { months: [9, 10, 11], timing: { 9: 'Late', 10: 'Middle to Late', 11: 'Early' } },
      growing: { months: [12, 1] },
      harvesting: { months: [2, 3], timing: { 2: 'Middle', 3: 'Early to Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'raj-gram',
    state: 'Rajasthan',
    season: 'Rabi',
    crop: 'Gram (Chana / Chickpea)',
    localName: 'चना',
    primaryCategory: 'Pulses',
    sowingWindow: 'October (Beginning) – November (Middle)',
    growingWindow: 'December – January',
    harvestingWindow: 'February (Late) – March (Late)',
    months: createMonthMap({
      sowing: { months: [10, 11], timing: { 10: 'Beginning to Middle', 11: 'Middle' } },
      growing: { months: [12, 1] },
      harvesting: { months: [2, 3], timing: { 2: 'Late', 3: 'Middle to Late' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'raj-moong',
    state: 'Rajasthan',
    season: 'Kharif',
    crop: 'Moong (Green Gram)',
    localName: 'मूंग',
    primaryCategory: 'Pulses',
    sowingWindow: 'June (Late) – July (Middle)',
    growingWindow: 'August',
    harvestingWindow: 'September (Middle) – October (Early)',
    months: createMonthMap({
      sowing: { months: [6, 7], timing: { 6: 'Late', 7: 'Middle' } },
      growing: { months: [8] },
      harvesting: { months: [9, 10], timing: { 9: 'Middle', 10: 'Early' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'raj-clusterbean',
    state: 'Rajasthan',
    season: 'Kharif',
    crop: 'Guar (Cluster Bean)',
    localName: 'ग्वार',
    primaryCategory: 'Commercial',
    sowingWindow: 'July (Early) – July (Late)',
    growingWindow: 'August – September',
    harvestingWindow: 'October (Beginning) – November (Early)',
    months: createMonthMap({
      sowing: { months: [7], timing: { 7: 'Beginning to Late' } },
      growing: { months: [8, 9] },
      harvesting: { months: [10, 11], timing: { 10: 'Middle', 11: 'Early' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'raj-cotton',
    state: 'Rajasthan',
    season: 'Kharif',
    crop: 'Cotton (Kapas)',
    localName: 'कपास',
    primaryCategory: 'Fibre',
    sowingWindow: 'April (Late) – May (Late)',
    growingWindow: 'June – September',
    harvestingWindow: 'October (Middle) – December (Late)',
    months: createMonthMap({
      sowing: { months: [4, 5], timing: { 4: 'Late', 5: 'Middle to Late' } },
      growing: { months: [6, 7, 8, 9] },
      harvesting: { months: [10, 11, 12], timing: { 10: 'Middle', 11: 'Middle', 12: 'Late' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'raj-barley',
    state: 'Rajasthan',
    season: 'Rabi',
    crop: 'Barley (Jau)',
    localName: 'जौ',
    primaryCategory: 'Foodgrain',
    sowingWindow: 'October (Late) – November (Late)',
    growingWindow: 'December – February',
    harvestingWindow: 'March (Early) – April (Beginning)',
    months: createMonthMap({
      sowing: { months: [10, 11], timing: { 10: 'Late', 11: 'Middle to Late' } },
      growing: { months: [12, 1, 2] },
      harvesting: { months: [3, 4], timing: { 3: 'Middle', 4: 'Beginning' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'raj-groundnut',
    state: 'Rajasthan',
    season: 'Kharif',
    crop: 'Groundnut (Peanut)',
    localName: 'मूंगफली',
    primaryCategory: 'Oilseeds',
    sowingWindow: 'May (Late) – June (Late)',
    growingWindow: 'July – September',
    harvestingWindow: 'October (Beginning) – November (Middle)',
    months: createMonthMap({
      sowing: { months: [5, 6], timing: { 5: 'Late', 6: 'Middle to Late' } },
      growing: { months: [7, 8, 9] },
      harvesting: { months: [10, 11], timing: { 10: 'Middle', 11: 'Early' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'raj-cumin',
    state: 'Rajasthan',
    season: 'Rabi',
    crop: 'Cumin (Jeera)',
    localName: 'जीरा',
    primaryCategory: 'Commercial',
    sowingWindow: 'November (Beginning) – November (Late)',
    growingWindow: 'December – January',
    harvestingWindow: 'February (Late) – March (Late)',
    months: createMonthMap({
      sowing: { months: [11], timing: { 11: 'Beginning to Late' } },
      growing: { months: [12, 1] },
      harvesting: { months: [2, 3], timing: { 2: 'Late', 3: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'raj-coriander',
    state: 'Rajasthan',
    season: 'Rabi',
    crop: 'Coriander (Dhaniya)',
    localName: 'धनिया',
    primaryCategory: 'Commercial',
    sowingWindow: 'October (Middle) – November (Middle)',
    growingWindow: 'December – January',
    harvestingWindow: 'February (Middle) – March (Late)',
    months: createMonthMap({
      sowing: { months: [10, 11], timing: { 10: 'Middle', 11: 'Middle' } },
      growing: { months: [12, 1] },
      harvesting: { months: [2, 3], timing: { 2: 'Middle', 3: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'raj-isabgol',
    state: 'Rajasthan',
    season: 'Rabi',
    crop: 'Isabgol (Psyllium)',
    localName: 'ईसबगोल',
    primaryCategory: 'Commercial',
    sowingWindow: 'October (Late) – November (Late)',
    growingWindow: 'December – January',
    harvestingWindow: 'March (Beginning) – March (Late)',
    months: createMonthMap({
      sowing: { months: [10, 11], timing: { 10: 'Late', 11: 'Middle' } },
      growing: { months: [12, 1] },
      harvesting: { months: [3], timing: { 3: 'Beginning to Late' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'raj-garlic',
    state: 'Rajasthan',
    season: 'Rabi',
    crop: 'Garlic (Lahsun)',
    localName: 'लहसुन',
    primaryCategory: 'Horticulture',
    sowingWindow: 'September (Late) – November (Early)',
    growingWindow: 'December – February',
    harvestingWindow: 'March (Early) – April (Late)',
    months: createMonthMap({
      sowing: { months: [9, 10, 11], timing: { 9: 'Late', 10: 'Middle', 11: 'Early' } },
      growing: { months: [12, 1, 2] },
      harvesting: { months: [3, 4], timing: { 3: 'Middle', 4: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'raj-onion',
    state: 'Rajasthan',
    season: 'Rabi',
    crop: 'Onion (Pyaj)',
    localName: 'प्याज',
    primaryCategory: 'Horticulture',
    sowingWindow: 'November (Beginning) – December (Late)',
    growingWindow: 'January – February',
    harvestingWindow: 'April (Beginning) – May (Middle)',
    months: createMonthMap({
      sowing: { months: [11, 12], timing: { 11: 'Middle', 12: 'Middle' } },
      growing: { months: [1, 2] },
      harvesting: { months: [4, 5], timing: { 4: 'Middle', 5: 'Early' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'raj-maize',
    state: 'Rajasthan',
    season: 'Kharif',
    crop: 'Maize (Makka)',
    localName: 'मक्का',
    primaryCategory: 'Foodgrain',
    sowingWindow: 'June (Late) – July (Middle)',
    growingWindow: 'August',
    harvestingWindow: 'September (Middle) – October (Late)',
    months: createMonthMap({
      sowing: { months: [6, 7], timing: { 6: 'Late', 7: 'Middle' } },
      growing: { months: [8] },
      harvesting: { months: [9, 10], timing: { 9: 'Middle', 10: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'raj-soybean',
    state: 'Rajasthan',
    season: 'Kharif',
    crop: 'Soybean',
    localName: 'सोयाबीन',
    primaryCategory: 'Oilseeds',
    sowingWindow: 'June (Late) – July (Middle)',
    growingWindow: 'August',
    harvestingWindow: 'September (Late) – October (Middle)',
    months: createMonthMap({
      sowing: { months: [6, 7], timing: { 6: 'Late', 7: 'Middle' } },
      growing: { months: [8] },
      harvesting: { months: [9, 10], timing: { 9: 'Late', 10: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },

  // ==================== PUNJAB ====================
  {
    id: 'pun-wheat',
    state: 'Punjab',
    season: 'Rabi',
    crop: 'Wheat',
    localName: 'गेहूं (ਕਣਕ)',
    primaryCategory: 'Foodgrain',
    sowingWindow: 'October (Late) – November (Late)',
    growingWindow: 'December – February',
    harvestingWindow: 'April (Beginning) – May (Early)',
    months: createMonthMap({
      sowing: { months: [10, 11], timing: { 10: 'Late', 11: 'Beginning to Late' } },
      growing: { months: [12, 1, 2, 3] },
      harvesting: { months: [4, 5], timing: { 4: 'Middle', 5: 'Early' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'pun-rice',
    state: 'Punjab',
    season: 'Kharif',
    crop: 'Rice (Paddy)',
    localName: 'धान (ਝੋਨਾ)',
    primaryCategory: 'Foodgrain',
    sowingWindow: 'June (Middle) – July (Early)',
    growingWindow: 'July – September',
    harvestingWindow: 'October (Beginning) – November (Middle)',
    months: createMonthMap({
      sowing: { months: [6, 7], timing: { 6: 'Middle to Late', 7: 'Early' } },
      growing: { months: [8, 9] },
      harvesting: { months: [10, 11], timing: { 10: 'Middle', 11: 'Early to Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'pun-cotton',
    state: 'Punjab',
    season: 'Kharif',
    crop: 'Cotton',
    localName: 'कपास (ਨਰਮਾ)',
    primaryCategory: 'Fibre',
    sowingWindow: 'April (Middle) – May (Late)',
    growingWindow: 'June – September',
    harvestingWindow: 'October (Early) – December (Beginning)',
    months: createMonthMap({
      sowing: { months: [4, 5], timing: { 4: 'Middle', 5: 'Late' } },
      growing: { months: [6, 7, 8, 9] },
      harvesting: { months: [10, 11, 12], timing: { 10: 'Middle', 11: 'Middle', 12: 'Beginning' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'pun-mustard',
    state: 'Punjab',
    season: 'Rabi',
    crop: 'Raya / Mustard',
    localName: 'सरसों / राया',
    primaryCategory: 'Oilseeds',
    sowingWindow: 'October (Beginning) – November (Early)',
    growingWindow: 'December – January',
    harvestingWindow: 'March (Early) – March (Late)',
    months: createMonthMap({
      sowing: { months: [10, 11], timing: { 10: 'Middle', 11: 'Early' } },
      growing: { months: [12, 1] },
      harvesting: { months: [3], timing: { 3: 'Early to Late' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'pun-potato',
    state: 'Punjab',
    season: 'Rabi',
    crop: 'Potato',
    localName: 'आलू (ਆਲੂ)',
    primaryCategory: 'Horticulture',
    sowingWindow: 'September (Late) – October (Late)',
    growingWindow: 'November – December',
    harvestingWindow: 'January (Early) – February (Late)',
    months: createMonthMap({
      sowing: { months: [9, 10], timing: { 9: 'Late', 10: 'Middle to Late' } },
      growing: { months: [11, 12] },
      harvesting: { months: [1, 2], timing: { 1: 'Early', 2: 'Middle to Late' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'pun-sugarcane',
    state: 'Punjab',
    season: 'Annual',
    crop: 'Sugarcane',
    localName: 'गन्ना (ਗੰਨਾ)',
    primaryCategory: 'Commercial',
    sowingWindow: 'February (Late) – March (Late)',
    growingWindow: 'April – October',
    harvestingWindow: 'November (Middle) – March (Middle)',
    months: createMonthMap({
      sowing: { months: [2, 3], timing: { 2: 'Late', 3: 'Middle to Late' } },
      growing: { months: [4, 5, 6, 7, 8, 9, 10] },
      harvesting: { months: [11, 12, 1], timing: { 11: 'Middle', 12: 'Late', 1: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'pun-maize',
    state: 'Punjab',
    season: 'Kharif',
    crop: 'Maize (Makki)',
    localName: 'मक्का (ਮੱਕੀ)',
    primaryCategory: 'Foodgrain',
    sowingWindow: 'May (Late) – June (Late)',
    growingWindow: 'July – August',
    harvestingWindow: 'August (Late) – September (Late)',
    months: createMonthMap({
      sowing: { months: [5, 6], timing: { 5: 'Late', 6: 'Middle' } },
      growing: { months: [7, 8] },
      harvesting: { months: [8, 9], timing: { 8: 'Late', 9: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'pun-moong',
    state: 'Punjab',
    season: 'Zaid / Summer',
    crop: 'Summer Moong',
    localName: 'मूंग (ਮੂੰਗੀ)',
    primaryCategory: 'Pulses',
    sowingWindow: 'March (Late) – April (Late)',
    growingWindow: 'May',
    harvestingWindow: 'June (Beginning) – June (Late)',
    months: createMonthMap({
      sowing: { months: [3, 4], timing: { 3: 'Late', 4: 'Middle' } },
      growing: { months: [5] },
      harvesting: { months: [6], timing: { 6: 'Beginning to Late' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'pun-sunflower',
    state: 'Punjab',
    season: 'Zaid / Summer',
    crop: 'Sunflower (Surajmukhi)',
    localName: 'सूरजमुखी (ਸੂਰਜਮੁਖੀ)',
    primaryCategory: 'Oilseeds',
    sowingWindow: 'January (Late) – February (Late)',
    growingWindow: 'March – April',
    harvestingWindow: 'May (Middle) – June (Early)',
    months: createMonthMap({
      sowing: { months: [1, 2], timing: { 1: 'Late', 2: 'Middle' } },
      growing: { months: [3, 4] },
      harvesting: { months: [5, 6], timing: { 5: 'Middle', 6: 'Early' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'pun-gram',
    state: 'Punjab',
    season: 'Rabi',
    crop: 'Gram (Chana / Chhole)',
    localName: 'चना (ਛੋਲੇ)',
    primaryCategory: 'Pulses',
    sowingWindow: 'October (Beginning) – November (Middle)',
    growingWindow: 'December – January',
    harvestingWindow: 'March (Late) – April (Late)',
    months: createMonthMap({
      sowing: { months: [10, 11], timing: { 10: 'Middle', 11: 'Early' } },
      growing: { months: [12, 1, 2] },
      harvesting: { months: [3, 4], timing: { 3: 'Late', 4: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'pun-barley',
    state: 'Punjab',
    season: 'Rabi',
    crop: 'Barley (Jau)',
    localName: 'जौ (ਜੌਂ)',
    primaryCategory: 'Foodgrain',
    sowingWindow: 'October (Late) – November (Late)',
    growingWindow: 'December – February',
    harvestingWindow: 'March (Late) – April (Middle)',
    months: createMonthMap({
      sowing: { months: [10, 11], timing: { 10: 'Late', 11: 'Middle' } },
      growing: { months: [12, 1, 2] },
      harvesting: { months: [3, 4], timing: { 3: 'Late', 4: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },

  // ==================== HARYANA ====================
  {
    id: 'har-wheat',
    state: 'Haryana',
    season: 'Rabi',
    crop: 'Wheat',
    localName: 'गेहूं',
    primaryCategory: 'Foodgrain',
    sowingWindow: 'October (Late) – December (Beginning)',
    growingWindow: 'January – February',
    harvestingWindow: 'April (Beginning) – April (Late)',
    months: createMonthMap({
      sowing: { months: [10, 11, 12], timing: { 10: 'Late', 11: 'Middle', 12: 'Beginning' } },
      growing: { months: [1, 2, 3] },
      harvesting: { months: [4], timing: { 4: 'Beginning to Late' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'har-rice',
    state: 'Haryana',
    season: 'Kharif',
    crop: 'Rice (Basmati & Non-Basmati)',
    localName: 'धान',
    primaryCategory: 'Foodgrain',
    sowingWindow: 'June (Middle) – July (Middle)',
    growingWindow: 'August – September',
    harvestingWindow: 'October (Early) – November (Late)',
    months: createMonthMap({
      sowing: { months: [6, 7], timing: { 6: 'Middle to Late', 7: 'Middle' } },
      growing: { months: [8, 9] },
      harvesting: { months: [10, 11], timing: { 10: 'Middle', 11: 'Early to Late' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'har-mustard',
    state: 'Haryana',
    season: 'Rabi',
    crop: 'Mustard',
    localName: 'सरसों',
    primaryCategory: 'Oilseeds',
    sowingWindow: 'September (Late) – October (Late)',
    growingWindow: 'November – January',
    harvestingWindow: 'February (Late) – March (Late)',
    months: createMonthMap({
      sowing: { months: [9, 10], timing: { 9: 'Late', 10: 'Middle to Late' } },
      growing: { months: [11, 12, 1] },
      harvesting: { months: [2, 3], timing: { 2: 'Late', 3: 'Middle to Late' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'har-cotton',
    state: 'Haryana',
    season: 'Kharif',
    crop: 'Cotton',
    localName: 'कपास',
    primaryCategory: 'Fibre',
    sowingWindow: 'April (Late) – May (Late)',
    growingWindow: 'June – September',
    harvestingWindow: 'October (Early) – December (Beginning)',
    months: createMonthMap({
      sowing: { months: [4, 5], timing: { 4: 'Late', 5: 'Middle to Late' } },
      growing: { months: [6, 7, 8, 9] },
      harvesting: { months: [10, 11, 12], timing: { 10: 'Middle', 11: 'Middle', 12: 'Beginning' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'har-bajra',
    state: 'Haryana',
    season: 'Kharif',
    crop: 'Bajra (Pearl Millet)',
    localName: 'बाजरा',
    primaryCategory: 'Foodgrain',
    sowingWindow: 'June (Late) – July (Late)',
    growingWindow: 'August',
    harvestingWindow: 'September (Middle) – October (Middle)',
    months: createMonthMap({
      sowing: { months: [6, 7], timing: { 6: 'Late', 7: 'Middle' } },
      growing: { months: [8] },
      harvesting: { months: [9, 10], timing: { 9: 'Middle', 10: 'Early' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'har-barley',
    state: 'Haryana',
    season: 'Rabi',
    crop: 'Barley (Jau)',
    localName: 'जौ',
    primaryCategory: 'Foodgrain',
    sowingWindow: 'October (Late) – November (Late)',
    growingWindow: 'December – February',
    harvestingWindow: 'March (Middle) – April (Late)',
    months: createMonthMap({
      sowing: { months: [10, 11], timing: { 10: 'Late', 11: 'Middle' } },
      growing: { months: [12, 1, 2] },
      harvesting: { months: [3, 4], timing: { 3: 'Middle', 4: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'har-gram',
    state: 'Haryana',
    season: 'Rabi',
    crop: 'Gram (Chana)',
    localName: 'चना',
    primaryCategory: 'Pulses',
    sowingWindow: 'October (Beginning) – November (Middle)',
    growingWindow: 'December – January',
    harvestingWindow: 'March (Early) – April (Middle)',
    months: createMonthMap({
      sowing: { months: [10, 11], timing: { 10: 'Middle', 11: 'Early' } },
      growing: { months: [12, 1] },
      harvesting: { months: [3, 4], timing: { 3: 'Middle', 4: 'Early' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'har-sugarcane',
    state: 'Haryana',
    season: 'Annual',
    crop: 'Sugarcane',
    localName: 'गन्ना',
    primaryCategory: 'Commercial',
    sowingWindow: 'February (Middle) – March (Late)',
    growingWindow: 'April – October',
    harvestingWindow: 'November (Beginning) – March (Middle)',
    months: createMonthMap({
      sowing: { months: [2, 3], timing: { 2: 'Middle', 3: 'Middle' } },
      growing: { months: [4, 5, 6, 7, 8, 9, 10] },
      harvesting: { months: [11, 12, 1], timing: { 11: 'Middle', 12: 'Middle', 1: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'har-sunflower',
    state: 'Haryana',
    season: 'Zaid / Summer',
    crop: 'Sunflower',
    localName: 'सूरजमुखी',
    primaryCategory: 'Oilseeds',
    sowingWindow: 'January (Late) – February (Late)',
    growingWindow: 'March – April',
    harvestingWindow: 'May (Beginning) – June (Early)',
    months: createMonthMap({
      sowing: { months: [1, 2], timing: { 1: 'Late', 2: 'Middle' } },
      growing: { months: [3, 4] },
      harvesting: { months: [5, 6], timing: { 5: 'Middle', 6: 'Early' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'har-potato',
    state: 'Haryana',
    season: 'Rabi',
    crop: 'Potato',
    localName: 'आलू',
    primaryCategory: 'Horticulture',
    sowingWindow: 'September (Late) – October (Late)',
    growingWindow: 'November – December',
    harvestingWindow: 'January (Early) – February (Late)',
    months: createMonthMap({
      sowing: { months: [9, 10], timing: { 9: 'Late', 10: 'Middle' } },
      growing: { months: [11, 12] },
      harvesting: { months: [1, 2], timing: { 1: 'Early', 2: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'har-guar',
    state: 'Haryana',
    season: 'Kharif',
    crop: 'Guar (Cluster Bean)',
    localName: 'ग्वार',
    primaryCategory: 'Commercial',
    sowingWindow: 'June (Late) – July (Late)',
    growingWindow: 'August – September',
    harvestingWindow: 'October (Beginning) – November (Middle)',
    months: createMonthMap({
      sowing: { months: [6, 7], timing: { 6: 'Late', 7: 'Middle' } },
      growing: { months: [8, 9] },
      harvesting: { months: [10, 11], timing: { 10: 'Middle', 11: 'Early' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },

  // ==================== UTTAR PRADESH ====================
  {
    id: 'up-wheat',
    state: 'Uttar Pradesh',
    season: 'Rabi',
    crop: 'Wheat',
    localName: 'गेहूं',
    primaryCategory: 'Foodgrain',
    sowingWindow: 'November (Early) – December (Late)',
    growingWindow: 'January – February',
    harvestingWindow: 'March (Late) – April (Late)',
    months: createMonthMap({
      sowing: { months: [11, 12], timing: { 11: 'Beginning to Middle', 12: 'Early' } },
      growing: { months: [1, 2] },
      harvesting: { months: [3, 4], timing: { 3: 'Late', 4: 'Middle to Late' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'up-rice',
    state: 'Uttar Pradesh',
    season: 'Kharif',
    crop: 'Rice (Paddy)',
    localName: 'धान',
    primaryCategory: 'Foodgrain',
    sowingWindow: 'June (Beginning) – July (Late)',
    growingWindow: 'August – September',
    harvestingWindow: 'October (Middle) – November (Late)',
    months: createMonthMap({
      sowing: { months: [6, 7], timing: { 6: 'Middle to Late', 7: 'Beginning to Late' } },
      growing: { months: [8, 9] },
      harvesting: { months: [10, 11], timing: { 10: 'Middle to Late', 11: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'up-sugarcane',
    state: 'Uttar Pradesh',
    season: 'Annual',
    crop: 'Sugarcane',
    localName: 'गन्ना',
    primaryCategory: 'Commercial',
    sowingWindow: 'October (Autumn) & February–March (Spring)',
    growingWindow: 'April – September',
    harvestingWindow: 'October (Late) – March (Late)',
    months: createMonthMap({
      sowing: { months: [10, 2, 3], timing: { 10: 'Middle', 2: 'Middle', 3: 'Middle' } },
      growing: { months: [4, 5, 6, 7, 8, 9] },
      harvesting: { months: [11, 12, 1], timing: { 11: 'Middle', 12: 'Late', 1: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'up-mustard',
    state: 'Uttar Pradesh',
    season: 'Rabi',
    crop: 'Mustard / Toria',
    localName: 'सरसों / तोरिया',
    primaryCategory: 'Oilseeds',
    sowingWindow: 'September (Middle) – October (Late)',
    growingWindow: 'November – December',
    harvestingWindow: 'February (Early) – March (Middle)',
    months: createMonthMap({
      sowing: { months: [9, 10], timing: { 9: 'Middle', 10: 'Early to Middle' } },
      growing: { months: [11, 12, 1] },
      harvesting: { months: [2, 3], timing: { 2: 'Middle', 3: 'Early' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'up-potato',
    state: 'Uttar Pradesh',
    season: 'Rabi',
    crop: 'Potato',
    localName: 'आलू',
    primaryCategory: 'Horticulture',
    sowingWindow: 'October (Beginning) – November (Middle)',
    growingWindow: 'December',
    harvestingWindow: 'January (Late) – March (Early)',
    months: createMonthMap({
      sowing: { months: [10, 11], timing: { 10: 'Middle', 11: 'Early' } },
      growing: { months: [12] },
      harvesting: { months: [1, 2, 3], timing: { 1: 'Late', 2: 'Middle', 3: 'Early' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'up-maize',
    state: 'Uttar Pradesh',
    season: 'Kharif',
    crop: 'Maize (Makka)',
    localName: 'मक्का',
    primaryCategory: 'Foodgrain',
    sowingWindow: 'June (Late) – July (Middle)',
    growingWindow: 'August',
    harvestingWindow: 'September (Late) – October (Middle)',
    months: createMonthMap({
      sowing: { months: [6, 7], timing: { 6: 'Late', 7: 'Middle' } },
      growing: { months: [8] },
      harvesting: { months: [9, 10], timing: { 9: 'Late', 10: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'up-gram',
    state: 'Uttar Pradesh',
    season: 'Rabi',
    crop: 'Gram (Chana / Chickpea)',
    localName: 'चना',
    primaryCategory: 'Pulses',
    sowingWindow: 'October (Beginning) – November (Middle)',
    growingWindow: 'December – January',
    harvestingWindow: 'March (Middle) – April (Late)',
    months: createMonthMap({
      sowing: { months: [10, 11], timing: { 10: 'Beginning to Middle', 11: 'Early' } },
      growing: { months: [12, 1, 2] },
      harvesting: { months: [3, 4], timing: { 3: 'Middle', 4: 'Late' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'up-masoor',
    state: 'Uttar Pradesh',
    season: 'Rabi',
    crop: 'Lentil (Masoor)',
    localName: 'मसूर',
    primaryCategory: 'Pulses',
    sowingWindow: 'October (Late) – November (Late)',
    growingWindow: 'December – January',
    harvestingWindow: 'March (Beginning) – April (Middle)',
    months: createMonthMap({
      sowing: { months: [10, 11], timing: { 10: 'Late', 11: 'Middle' } },
      growing: { months: [12, 1, 2] },
      harvesting: { months: [3, 4], timing: { 3: 'Beginning to Middle', 4: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'up-tur',
    state: 'Uttar Pradesh',
    season: 'Kharif',
    crop: 'Tur / Arhar (Pigeon Pea)',
    localName: 'अरहर',
    primaryCategory: 'Pulses',
    sowingWindow: 'June (Middle) – July (Middle)',
    growingWindow: 'August – November',
    harvestingWindow: 'December (Middle) – January (Late)',
    months: createMonthMap({
      sowing: { months: [6, 7], timing: { 6: 'Middle to Late', 7: 'Middle' } },
      growing: { months: [8, 9, 10, 11] },
      harvesting: { months: [12, 1], timing: { 12: 'Middle', 1: 'Middle to Late' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'up-moong',
    state: 'Uttar Pradesh',
    season: 'Zaid / Summer',
    crop: 'Moong (Green Gram)',
    localName: 'मूंग',
    primaryCategory: 'Pulses',
    sowingWindow: 'March (Late) – April (Middle)',
    growingWindow: 'April – May',
    harvestingWindow: 'May (Late) – June (Middle)',
    months: createMonthMap({
      sowing: { months: [3, 4], timing: { 3: 'Late', 4: 'Middle' } },
      growing: { months: [5] },
      harvesting: { months: [5, 6], timing: { 5: 'Late', 6: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'up-urad',
    state: 'Uttar Pradesh',
    season: 'Kharif',
    crop: 'Urad (Black Gram)',
    localName: 'उड़द',
    primaryCategory: 'Pulses',
    sowingWindow: 'June (Late) – July (Late)',
    growingWindow: 'August',
    harvestingWindow: 'September (Late) – October (Late)',
    months: createMonthMap({
      sowing: { months: [6, 7], timing: { 6: 'Late', 7: 'Middle to Late' } },
      growing: { months: [8] },
      harvesting: { months: [9, 10], timing: { 9: 'Late', 10: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'up-groundnut',
    state: 'Uttar Pradesh',
    season: 'Kharif',
    crop: 'Groundnut (Peanut)',
    localName: 'मूंगफली',
    primaryCategory: 'Oilseeds',
    sowingWindow: 'June (Middle) – July (Early)',
    growingWindow: 'August – September',
    harvestingWindow: 'October (Middle) – November (Early)',
    months: createMonthMap({
      sowing: { months: [6, 7], timing: { 6: 'Middle', 7: 'Early' } },
      growing: { months: [8, 9] },
      harvesting: { months: [10, 11], timing: { 10: 'Middle', 11: 'Early' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'up-bajra',
    state: 'Uttar Pradesh',
    season: 'Kharif',
    crop: 'Bajra (Pearl Millet)',
    localName: 'बाजरा',
    primaryCategory: 'Foodgrain',
    sowingWindow: 'June (Late) – July (Late)',
    growingWindow: 'August',
    harvestingWindow: 'September (Late) – October (Middle)',
    months: createMonthMap({
      sowing: { months: [6, 7], timing: { 6: 'Late', 7: 'Middle to Late' } },
      growing: { months: [8] },
      harvesting: { months: [9, 10], timing: { 9: 'Late', 10: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'up-barley',
    state: 'Uttar Pradesh',
    season: 'Rabi',
    crop: 'Barley (Jau)',
    localName: 'जौ',
    primaryCategory: 'Foodgrain',
    sowingWindow: 'October (Late) – November (Late)',
    growingWindow: 'December – February',
    harvestingWindow: 'March (Middle) – April (Early)',
    months: createMonthMap({
      sowing: { months: [10, 11], timing: { 10: 'Late', 11: 'Middle' } },
      growing: { months: [12, 1, 2] },
      harvesting: { months: [3, 4], timing: { 3: 'Middle', 4: 'Early' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'up-onion',
    state: 'Uttar Pradesh',
    season: 'Rabi',
    crop: 'Onion (Pyaj)',
    localName: 'प्याज',
    primaryCategory: 'Horticulture',
    sowingWindow: 'November (Beginning) – December (Late)',
    growingWindow: 'January – February',
    harvestingWindow: 'April (Middle) – May (Middle)',
    months: createMonthMap({
      sowing: { months: [11, 12], timing: { 11: 'Middle', 12: 'Middle' } },
      growing: { months: [1, 2, 3] },
      harvesting: { months: [4, 5], timing: { 4: 'Middle', 5: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'up-garlic',
    state: 'Uttar Pradesh',
    season: 'Rabi',
    crop: 'Garlic (Lahsun)',
    localName: 'लहसुन',
    primaryCategory: 'Horticulture',
    sowingWindow: 'October (Beginning) – November (Middle)',
    growingWindow: 'December – February',
    harvestingWindow: 'March (Middle) – April (Late)',
    months: createMonthMap({
      sowing: { months: [10, 11], timing: { 10: 'Beginning to Middle', 11: 'Early' } },
      growing: { months: [12, 1, 2] },
      harvesting: { months: [3, 4], timing: { 3: 'Middle', 4: 'Late' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },

  // ==================== MADHYA PRADESH ====================
  {
    id: 'mp-soybean',
    state: 'Madhya Pradesh',
    season: 'Kharif',
    crop: 'Soybean',
    localName: 'सोयाबीन',
    primaryCategory: 'Oilseeds',
    sowingWindow: 'June (Middle) – July (Middle)',
    growingWindow: 'August',
    harvestingWindow: 'September (Late) – October (Late)',
    months: createMonthMap({
      sowing: { months: [6, 7], timing: { 6: 'Late', 7: 'Early to Middle' } },
      growing: { months: [8] },
      harvesting: { months: [9, 10], timing: { 9: 'Late', 10: 'Early to Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'mp-wheat',
    state: 'Madhya Pradesh',
    season: 'Rabi',
    crop: 'Wheat (Sharbati & Durum)',
    localName: 'गेहूं',
    primaryCategory: 'Foodgrain',
    sowingWindow: 'October (Late) – November (Late)',
    growingWindow: 'December – January',
    harvestingWindow: 'February (Late) – March (Late)',
    months: createMonthMap({
      sowing: { months: [10, 11], timing: { 10: 'Late', 11: 'Middle' } },
      growing: { months: [12, 1] },
      harvesting: { months: [2, 3], timing: { 2: 'Late', 3: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'mp-gram',
    state: 'Madhya Pradesh',
    season: 'Rabi',
    crop: 'Gram (Chana)',
    localName: 'चना',
    primaryCategory: 'Pulses',
    sowingWindow: 'October (Beginning) – November (Middle)',
    growingWindow: 'December – January',
    harvestingWindow: 'February (Middle) – March (Late)',
    months: createMonthMap({
      sowing: { months: [10, 11], timing: { 10: 'Beginning to Middle', 11: 'Early' } },
      growing: { months: [12, 1] },
      harvesting: { months: [2, 3], timing: { 2: 'Middle', 3: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'mp-tur',
    state: 'Madhya Pradesh',
    season: 'Kharif',
    crop: 'Tur / Arhar (Pigeon Pea)',
    localName: 'अरहर / तुअर',
    primaryCategory: 'Pulses',
    sowingWindow: 'June (Late) – July (Middle)',
    growingWindow: 'August – November',
    harvestingWindow: 'December (Middle) – January (Late)',
    months: createMonthMap({
      sowing: { months: [6, 7], timing: { 6: 'Late', 7: 'Middle' } },
      growing: { months: [8, 9, 10, 11] },
      harvesting: { months: [12, 1], timing: { 12: 'Middle', 1: 'Middle to Late' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'mp-mustard',
    state: 'Madhya Pradesh',
    season: 'Rabi',
    crop: 'Mustard (Sarson)',
    localName: 'सरसों',
    primaryCategory: 'Oilseeds',
    sowingWindow: 'October (Early) – November (Early)',
    growingWindow: 'December – January',
    harvestingWindow: 'February (Late) – March (Late)',
    months: createMonthMap({
      sowing: { months: [10, 11], timing: { 10: 'Beginning to Middle', 11: 'Early' } },
      growing: { months: [12, 1] },
      harvesting: { months: [2, 3], timing: { 2: 'Late', 3: 'Middle to Late' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'mp-maize',
    state: 'Madhya Pradesh',
    season: 'Kharif',
    crop: 'Maize (Makka)',
    localName: 'मक्का',
    primaryCategory: 'Foodgrain',
    sowingWindow: 'June (Middle) – July (Middle)',
    growingWindow: 'August',
    harvestingWindow: 'September (Late) – October (Middle)',
    months: createMonthMap({
      sowing: { months: [6, 7], timing: { 6: 'Late', 7: 'Middle' } },
      growing: { months: [8] },
      harvesting: { months: [9, 10], timing: { 9: 'Late', 10: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'mp-garlic',
    state: 'Madhya Pradesh',
    season: 'Rabi',
    crop: 'Garlic (Lahsun)',
    localName: 'लहसुन',
    primaryCategory: 'Horticulture',
    sowingWindow: 'September (Late) – November (Beginning)',
    growingWindow: 'December – February',
    harvestingWindow: 'March (Beginning) – April (Middle)',
    months: createMonthMap({
      sowing: { months: [9, 10, 11], timing: { 9: 'Late', 10: 'Middle', 11: 'Beginning' } },
      growing: { months: [12, 1, 2] },
      harvesting: { months: [3, 4], timing: { 3: 'Beginning to Middle', 4: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'mp-onion',
    state: 'Madhya Pradesh',
    season: 'Rabi',
    crop: 'Onion (Pyaj)',
    localName: 'प्याज',
    primaryCategory: 'Horticulture',
    sowingWindow: 'November (Beginning) – December (Middle)',
    growingWindow: 'January – February',
    harvestingWindow: 'April (Early) – May (Early)',
    months: createMonthMap({
      sowing: { months: [11, 12], timing: { 11: 'Middle', 12: 'Early to Middle' } },
      growing: { months: [1, 2] },
      harvesting: { months: [4, 5], timing: { 4: 'Middle', 5: 'Early' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'mp-moong',
    state: 'Madhya Pradesh',
    season: 'Zaid / Summer',
    crop: 'Moong (Green Gram)',
    localName: 'मूंग',
    primaryCategory: 'Pulses',
    sowingWindow: 'March (Middle) – April (Early)',
    growingWindow: 'April – May',
    harvestingWindow: 'May (Late) – June (Middle)',
    months: createMonthMap({
      sowing: { months: [3, 4], timing: { 3: 'Middle to Late', 4: 'Early' } },
      growing: { months: [5] },
      harvesting: { months: [5, 6], timing: { 5: 'Late', 6: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'mp-masoor',
    state: 'Madhya Pradesh',
    season: 'Rabi',
    crop: 'Lentil (Masoor)',
    localName: 'मसूर',
    primaryCategory: 'Pulses',
    sowingWindow: 'October (Middle) – November (Middle)',
    growingWindow: 'December – January',
    harvestingWindow: 'February (Late) – March (Late)',
    months: createMonthMap({
      sowing: { months: [10, 11], timing: { 10: 'Middle', 11: 'Middle' } },
      growing: { months: [12, 1] },
      harvesting: { months: [2, 3], timing: { 2: 'Late', 3: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'mp-cotton',
    state: 'Madhya Pradesh',
    season: 'Kharif',
    crop: 'Cotton (Kapas)',
    localName: 'कपास',
    primaryCategory: 'Fibre',
    sowingWindow: 'May (Late) – June (Late)',
    growingWindow: 'July – October',
    harvestingWindow: 'November (Beginning) – January (Middle)',
    months: createMonthMap({
      sowing: { months: [5, 6], timing: { 5: 'Late', 6: 'Middle to Late' } },
      growing: { months: [7, 8, 9, 10] },
      harvesting: { months: [11, 12, 1], timing: { 11: 'Beginning', 12: 'Middle', 1: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'mp-groundnut',
    state: 'Madhya Pradesh',
    season: 'Kharif',
    crop: 'Groundnut (Peanut)',
    localName: 'मूंगफली',
    primaryCategory: 'Oilseeds',
    sowingWindow: 'June (Middle) – July (Middle)',
    growingWindow: 'August – September',
    harvestingWindow: 'October (Beginning) – November (Middle)',
    months: createMonthMap({
      sowing: { months: [6, 7], timing: { 6: 'Middle to Late', 7: 'Middle' } },
      growing: { months: [8, 9] },
      harvesting: { months: [10, 11], timing: { 10: 'Beginning', 11: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'mp-coriander',
    state: 'Madhya Pradesh',
    season: 'Rabi',
    crop: 'Coriander (Dhaniya)',
    localName: 'धनिया',
    primaryCategory: 'Commercial',
    sowingWindow: 'October (Beginning) – November (Early)',
    growingWindow: 'December – January',
    harvestingWindow: 'February (Middle) – March (Late)',
    months: createMonthMap({
      sowing: { months: [10, 11], timing: { 10: 'Beginning to Middle', 11: 'Early' } },
      growing: { months: [12, 1] },
      harvesting: { months: [2, 3], timing: { 2: 'Middle', 3: 'Late' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'mp-paddy',
    state: 'Madhya Pradesh',
    season: 'Kharif',
    crop: 'Rice (Dhan)',
    localName: 'धान',
    primaryCategory: 'Foodgrain',
    sowingWindow: 'June (Middle) – July (Late)',
    growingWindow: 'August – September',
    harvestingWindow: 'October (Late) – November (Late)',
    months: createMonthMap({
      sowing: { months: [6, 7], timing: { 6: 'Late', 7: 'Middle to Late' } },
      growing: { months: [8, 9] },
      harvesting: { months: [10, 11], timing: { 10: 'Late', 11: 'Middle to Late' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },

  // ==================== GUJARAT ====================
  {
    id: 'guj-cotton',
    state: 'Gujarat',
    season: 'Kharif',
    crop: 'Cotton',
    localName: 'कपास (કપાસ)',
    primaryCategory: 'Fibre',
    sowingWindow: 'June (Early) – July (Late)',
    growingWindow: 'August – October',
    harvestingWindow: 'November (Beginning) – January (Late)',
    months: createMonthMap({
      sowing: { months: [6, 7], timing: { 6: 'Middle', 7: 'Middle' } },
      growing: { months: [8, 9, 10] },
      harvesting: { months: [11, 12, 1], timing: { 11: 'Beginning', 12: 'Middle', 1: 'Late' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'guj-groundnut',
    state: 'Gujarat',
    season: 'Kharif',
    crop: 'Groundnut (Peanut)',
    localName: 'मूंगफली (મગફળી)',
    primaryCategory: 'Oilseeds',
    sowingWindow: 'June (Middle) – July (Late)',
    growingWindow: 'August – September',
    harvestingWindow: 'October (Beginning) – November (Middle)',
    months: createMonthMap({
      sowing: { months: [6, 7], timing: { 6: 'Middle to Late', 7: 'Middle' } },
      growing: { months: [8, 9] },
      harvesting: { months: [10, 11], timing: { 10: 'Beginning to Middle', 11: 'Early' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'guj-castor',
    state: 'Gujarat',
    season: 'Kharif',
    crop: 'Castor Seed (Arandi)',
    localName: 'अरंडी (દિવેલા)',
    primaryCategory: 'Oilseeds',
    sowingWindow: 'July (Middle) – August (Late)',
    growingWindow: 'September – November',
    harvestingWindow: 'December (Beginning) – February (Late)',
    months: createMonthMap({
      sowing: { months: [7, 8], timing: { 7: 'Middle', 8: 'Middle' } },
      growing: { months: [9, 10, 11] },
      harvesting: { months: [12, 1, 2], timing: { 12: 'Beginning', 1: 'Middle', 2: 'Late' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'guj-wheat',
    state: 'Gujarat',
    season: 'Rabi',
    crop: 'Wheat',
    localName: 'गेहूं (ઘઉં)',
    primaryCategory: 'Foodgrain',
    sowingWindow: 'November (Beginning) – December (Beginning)',
    growingWindow: 'December – January',
    harvestingWindow: 'February (Late) – March (Late)',
    months: createMonthMap({
      sowing: { months: [11, 12], timing: { 11: 'Middle', 12: 'Beginning' } },
      growing: { months: [1] },
      harvesting: { months: [2, 3], timing: { 2: 'Late', 3: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'guj-cumin',
    state: 'Gujarat',
    season: 'Rabi',
    crop: 'Cumin (Jeera)',
    localName: 'जीरा (જીરું)',
    primaryCategory: 'Commercial',
    sowingWindow: 'November (Beginning) – November (Late)',
    growingWindow: 'December – January',
    harvestingWindow: 'February (Late) – March (Late)',
    months: createMonthMap({
      sowing: { months: [11], timing: { 11: 'Beginning to Late' } },
      growing: { months: [12, 1] },
      harvesting: { months: [2, 3], timing: { 2: 'Late', 3: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'guj-sesame',
    state: 'Gujarat',
    season: 'Kharif',
    crop: 'Sesame (Til)',
    localName: 'तिल (તલ)',
    primaryCategory: 'Oilseeds',
    sowingWindow: 'June (Late) – July (Middle)',
    growingWindow: 'August',
    harvestingWindow: 'September (Late) – October (Middle)',
    months: createMonthMap({
      sowing: { months: [6, 7], timing: { 6: 'Late', 7: 'Middle' } },
      growing: { months: [8] },
      harvesting: { months: [9, 10], timing: { 9: 'Late', 10: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'guj-bajra',
    state: 'Gujarat',
    season: 'Kharif',
    crop: 'Bajra (Pearl Millet)',
    localName: 'बाजरा (બાજરી)',
    primaryCategory: 'Foodgrain',
    sowingWindow: 'June (Late) – July (Late)',
    growingWindow: 'August',
    harvestingWindow: 'September (Middle) – October (Middle)',
    months: createMonthMap({
      sowing: { months: [6, 7], timing: { 6: 'Late', 7: 'Middle' } },
      growing: { months: [8] },
      harvesting: { months: [9, 10], timing: { 9: 'Middle', 10: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'guj-maize',
    state: 'Gujarat',
    season: 'Kharif',
    crop: 'Maize (Makka)',
    localName: 'मक्का (મકાઈ)',
    primaryCategory: 'Foodgrain',
    sowingWindow: 'June (Middle) – July (Middle)',
    growingWindow: 'August',
    harvestingWindow: 'September (Middle) – October (Late)',
    months: createMonthMap({
      sowing: { months: [6, 7], timing: { 6: 'Middle to Late', 7: 'Middle' } },
      growing: { months: [8] },
      harvesting: { months: [9, 10], timing: { 9: 'Middle', 10: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'guj-onion',
    state: 'Gujarat',
    season: 'Rabi',
    crop: 'Onion (Pyaj)',
    localName: 'प्याज (ડુંગળી)',
    primaryCategory: 'Horticulture',
    sowingWindow: 'October (Middle) – December (Beginning)',
    growingWindow: 'January – February',
    harvestingWindow: 'March (Late) – April (Late)',
    months: createMonthMap({
      sowing: { months: [10, 11, 12], timing: { 10: 'Middle', 11: 'Middle', 12: 'Beginning' } },
      growing: { months: [1, 2] },
      harvesting: { months: [3, 4], timing: { 3: 'Late', 4: 'Middle to Late' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'guj-potato',
    state: 'Gujarat',
    season: 'Rabi',
    crop: 'Potato (Alu)',
    localName: 'आलू (બટાકા)',
    primaryCategory: 'Horticulture',
    sowingWindow: 'November (Beginning) – November (Late)',
    growingWindow: 'December – January',
    harvestingWindow: 'February (Late) – March (Late)',
    months: createMonthMap({
      sowing: { months: [11], timing: { 11: 'Beginning to Late' } },
      growing: { months: [12, 1] },
      harvesting: { months: [2, 3], timing: { 2: 'Late', 3: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'guj-soybean',
    state: 'Gujarat',
    season: 'Kharif',
    crop: 'Soybean',
    localName: 'सोयाबीन',
    primaryCategory: 'Oilseeds',
    sowingWindow: 'June (Middle) – July (Middle)',
    growingWindow: 'August',
    harvestingWindow: 'September (Late) – October (Middle)',
    months: createMonthMap({
      sowing: { months: [6, 7], timing: { 6: 'Late', 7: 'Middle' } },
      growing: { months: [8] },
      harvesting: { months: [9, 10], timing: { 9: 'Late', 10: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'guj-fennel',
    state: 'Gujarat',
    season: 'Rabi',
    crop: 'Fennel (Saunf)',
    localName: 'सौंफ (વરિયાળી)',
    primaryCategory: 'Commercial',
    sowingWindow: 'October (Middle) – November (Middle)',
    growingWindow: 'December – February',
    harvestingWindow: 'March (Middle) – April (Late)',
    months: createMonthMap({
      sowing: { months: [10, 11], timing: { 10: 'Middle', 11: 'Middle' } },
      growing: { months: [12, 1, 2] },
      harvesting: { months: [3, 4], timing: { 3: 'Middle', 4: 'Middle to Late' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'guj-gram',
    state: 'Gujarat',
    season: 'Rabi',
    crop: 'Gram (Chana)',
    localName: 'चना (ચણા)',
    primaryCategory: 'Pulses',
    sowingWindow: 'October (Late) – November (Late)',
    growingWindow: 'December – January',
    harvestingWindow: 'February (Late) – March (Middle)',
    months: createMonthMap({
      sowing: { months: [10, 11], timing: { 10: 'Late', 11: 'Middle' } },
      growing: { months: [12, 1] },
      harvesting: { months: [2, 3], timing: { 2: 'Late', 3: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },

  // ==================== MAHARASHTRA ====================
  {
    id: 'mah-soybean',
    state: 'Maharashtra',
    season: 'Kharif',
    crop: 'Soybean',
    localName: 'सोयाबीन',
    primaryCategory: 'Oilseeds',
    sowingWindow: 'June (Middle) – July (Middle)',
    growingWindow: 'August',
    harvestingWindow: 'September (Late) – October (Late)',
    months: createMonthMap({
      sowing: { months: [6, 7], timing: { 6: 'Middle to Late', 7: 'Middle' } },
      growing: { months: [8] },
      harvesting: { months: [9, 10], timing: { 9: 'Late', 10: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'mah-cotton',
    state: 'Maharashtra',
    season: 'Kharif',
    crop: 'Cotton',
    localName: 'कपास (कापूस)',
    primaryCategory: 'Fibre',
    sowingWindow: 'June (Beginning) – July (Middle)',
    growingWindow: 'August – October',
    harvestingWindow: 'November (Middle) – January (Late)',
    months: createMonthMap({
      sowing: { months: [6, 7], timing: { 6: 'Beginning to Middle', 7: 'Early' } },
      growing: { months: [8, 9, 10] },
      harvesting: { months: [11, 12, 1], timing: { 11: 'Middle', 12: 'Middle', 1: 'Late' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'mah-jowar-rabi',
    state: 'Maharashtra',
    season: 'Rabi',
    crop: 'Jowar (Sorghum)',
    localName: 'ज्वार (ज्वारी)',
    primaryCategory: 'Foodgrain',
    sowingWindow: 'September (Middle) – October (Late)',
    growingWindow: 'November – December',
    harvestingWindow: 'January (Late) – February (Late)',
    months: createMonthMap({
      sowing: { months: [9, 10], timing: { 9: 'Middle', 10: 'Middle' } },
      growing: { months: [11, 12] },
      harvesting: { months: [1, 2], timing: { 1: 'Late', 2: 'Middle to Late' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'mah-onion',
    state: 'Maharashtra',
    season: 'Rabi',
    crop: 'Onion (Late Kharif & Rabi)',
    localName: 'प्याज (कांदा)',
    primaryCategory: 'Horticulture',
    sowingWindow: 'October (Middle) – December (Early)',
    growingWindow: 'January – February',
    harvestingWindow: 'March (Beginning) – April (Late)',
    months: createMonthMap({
      sowing: { months: [10, 11, 12], timing: { 10: 'Middle', 11: 'Middle', 12: 'Early' } },
      growing: { months: [1, 2] },
      harvesting: { months: [3, 4], timing: { 3: 'Beginning to Middle', 4: 'Late' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'mah-sugarcane',
    state: 'Maharashtra',
    season: 'Annual',
    crop: 'Sugarcane (Us)',
    localName: 'गन्ना (ऊस)',
    primaryCategory: 'Commercial',
    sowingWindow: 'July (Adsali) & January–February (Suru)',
    growingWindow: 'March – October',
    harvestingWindow: 'November (Beginning) – April (Late)',
    months: createMonthMap({
      sowing: { months: [7, 1, 2], timing: { 7: 'Middle', 1: 'Middle', 2: 'Middle' } },
      growing: { months: [3, 4, 5, 6, 8, 9, 10] },
      harvesting: { months: [11, 12, 1], timing: { 11: 'Middle', 12: 'Middle', 1: 'Late' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'mah-gram',
    state: 'Maharashtra',
    season: 'Rabi',
    crop: 'Gram (Chana / Harbara)',
    localName: 'चना (हरभरा)',
    primaryCategory: 'Pulses',
    sowingWindow: 'October (Beginning) – November (Middle)',
    growingWindow: 'December – January',
    harvestingWindow: 'February (Middle) – March (Late)',
    months: createMonthMap({
      sowing: { months: [10, 11], timing: { 10: 'Beginning to Middle', 11: 'Early' } },
      growing: { months: [12, 1] },
      harvesting: { months: [2, 3], timing: { 2: 'Middle', 3: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'mah-tur',
    state: 'Maharashtra',
    season: 'Kharif',
    crop: 'Tur / Arhar (Pigeon Pea)',
    localName: 'अरहर (तूर)',
    primaryCategory: 'Pulses',
    sowingWindow: 'June (Middle) – July (Middle)',
    growingWindow: 'August – November',
    harvestingWindow: 'December (Middle) – January (Late)',
    months: createMonthMap({
      sowing: { months: [6, 7], timing: { 6: 'Late', 7: 'Middle' } },
      growing: { months: [8, 9, 10, 11] },
      harvesting: { months: [12, 1], timing: { 12: 'Middle', 1: 'Middle to Late' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'mah-maize',
    state: 'Maharashtra',
    season: 'Kharif',
    crop: 'Maize (Makka)',
    localName: 'मक्का (मका)',
    primaryCategory: 'Foodgrain',
    sowingWindow: 'June (Late) – July (Middle)',
    growingWindow: 'August',
    harvestingWindow: 'September (Late) – October (Late)',
    months: createMonthMap({
      sowing: { months: [6, 7], timing: { 6: 'Late', 7: 'Middle' } },
      growing: { months: [8] },
      harvesting: { months: [9, 10], timing: { 9: 'Late', 10: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'mah-groundnut',
    state: 'Maharashtra',
    season: 'Kharif',
    crop: 'Groundnut (Bhuimug)',
    localName: 'मूंगफली (भुईमूग)',
    primaryCategory: 'Oilseeds',
    sowingWindow: 'June (Middle) – July (Early)',
    growingWindow: 'August – September',
    harvestingWindow: 'October (Early) – November (Beginning)',
    months: createMonthMap({
      sowing: { months: [6, 7], timing: { 6: 'Middle to Late', 7: 'Early' } },
      growing: { months: [8, 9] },
      harvesting: { months: [10, 11], timing: { 10: 'Early to Middle', 11: 'Beginning' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'mah-bajra',
    state: 'Maharashtra',
    season: 'Kharif',
    crop: 'Bajra (Pearl Millet)',
    localName: 'बाजरा (बाजरी)',
    primaryCategory: 'Foodgrain',
    sowingWindow: 'June (Late) – July (Middle)',
    growingWindow: 'August',
    harvestingWindow: 'September (Middle) – October (Early)',
    months: createMonthMap({
      sowing: { months: [6, 7], timing: { 6: 'Late', 7: 'Middle' } },
      growing: { months: [8] },
      harvesting: { months: [9, 10], timing: { 9: 'Middle', 10: 'Beginning' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'mah-wheat',
    state: 'Maharashtra',
    season: 'Rabi',
    crop: 'Wheat (Gahu)',
    localName: 'गेहूं (गहू)',
    primaryCategory: 'Foodgrain',
    sowingWindow: 'October (Late) – November (Late)',
    growingWindow: 'December – January',
    harvestingWindow: 'February (Late) – March (Middle)',
    months: createMonthMap({
      sowing: { months: [10, 11], timing: { 10: 'Late', 11: 'Middle' } },
      growing: { months: [12, 1] },
      harvesting: { months: [2, 3], timing: { 2: 'Late', 3: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'mah-rice',
    state: 'Maharashtra',
    season: 'Kharif',
    crop: 'Rice (Bhat)',
    localName: 'धान (भात)',
    primaryCategory: 'Foodgrain',
    sowingWindow: 'June (Beginning) – July (Middle)',
    growingWindow: 'August – September',
    harvestingWindow: 'October (Middle) – November (Late)',
    months: createMonthMap({
      sowing: { months: [6, 7], timing: { 6: 'Beginning to Middle', 7: 'Middle' } },
      growing: { months: [8, 9] },
      harvesting: { months: [10, 11], timing: { 10: 'Middle', 11: 'Late' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },

  // ==================== BIHAR ====================
  {
    id: 'bih-rice',
    state: 'Bihar',
    season: 'Kharif',
    crop: 'Rice (Paddy)',
    localName: 'धान',
    primaryCategory: 'Foodgrain',
    sowingWindow: 'June (Middle) – July (Late)',
    growingWindow: 'August – September',
    harvestingWindow: 'October (Late) – November (Late)',
    months: createMonthMap({
      sowing: { months: [6, 7], timing: { 6: 'Late', 7: 'Middle to Late' } },
      growing: { months: [8, 9] },
      harvesting: { months: [10, 11], timing: { 10: 'Late', 11: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'bih-maize',
    state: 'Bihar',
    season: 'Rabi',
    crop: 'Rabi Maize (Corn)',
    localName: 'मक्का',
    primaryCategory: 'Foodgrain',
    sowingWindow: 'October (Late) – November (Late)',
    growingWindow: 'December – February',
    harvestingWindow: 'March (Late) – April (Late)',
    months: createMonthMap({
      sowing: { months: [10, 11], timing: { 10: 'Late', 11: 'Middle' } },
      growing: { months: [12, 1, 2] },
      harvesting: { months: [3, 4], timing: { 3: 'Late', 4: 'Middle to Late' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'bih-wheat',
    state: 'Bihar',
    season: 'Rabi',
    crop: 'Wheat',
    localName: 'गेहूं',
    primaryCategory: 'Foodgrain',
    sowingWindow: 'November (Middle) – December (Late)',
    growingWindow: 'January – February',
    harvestingWindow: 'March (Late) – April (Middle)',
    months: createMonthMap({
      sowing: { months: [11, 12], timing: { 11: 'Middle to Late', 12: 'Middle' } },
      growing: { months: [1, 2] },
      harvesting: { months: [3, 4], timing: { 3: 'Late', 4: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'bih-masoor',
    state: 'Bihar',
    season: 'Rabi',
    crop: 'Lentil (Masoor)',
    localName: 'मसूर',
    primaryCategory: 'Pulses',
    sowingWindow: 'October (Late) – November (Late)',
    growingWindow: 'December – January',
    harvestingWindow: 'March (Beginning) – April (Middle)',
    months: createMonthMap({
      sowing: { months: [10, 11], timing: { 10: 'Late', 11: 'Middle' } },
      growing: { months: [12, 1] },
      harvesting: { months: [3, 4], timing: { 3: 'Beginning to Middle', 4: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'bih-gram',
    state: 'Bihar',
    season: 'Rabi',
    crop: 'Gram (Chana)',
    localName: 'चना',
    primaryCategory: 'Pulses',
    sowingWindow: 'October (Middle) – November (Middle)',
    growingWindow: 'December – January',
    harvestingWindow: 'March (Early) – April (Middle)',
    months: createMonthMap({
      sowing: { months: [10, 11], timing: { 10: 'Middle', 11: 'Middle' } },
      growing: { months: [12, 1] },
      harvesting: { months: [3, 4], timing: { 3: 'Early', 4: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'bih-potato',
    state: 'Bihar',
    season: 'Rabi',
    crop: 'Potato (Alu)',
    localName: 'आलू',
    primaryCategory: 'Horticulture',
    sowingWindow: 'October (Late) – November (Middle)',
    growingWindow: 'December',
    harvestingWindow: 'January (Late) – March (Early)',
    months: createMonthMap({
      sowing: { months: [10, 11], timing: { 10: 'Late', 11: 'Middle' } },
      growing: { months: [12] },
      harvesting: { months: [1, 2, 3], timing: { 1: 'Late', 2: 'Middle', 3: 'Early' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'bih-mustard',
    state: 'Bihar',
    season: 'Rabi',
    crop: 'Mustard (Sarson / Rai)',
    localName: 'सरसों',
    primaryCategory: 'Oilseeds',
    sowingWindow: 'October (Beginning) – November (Early)',
    growingWindow: 'December – January',
    harvestingWindow: 'February (Late) – March (Middle)',
    months: createMonthMap({
      sowing: { months: [10, 11], timing: { 10: 'Beginning to Middle', 11: 'Early' } },
      growing: { months: [12, 1] },
      harvesting: { months: [2, 3], timing: { 2: 'Late', 3: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'bih-sugarcane',
    state: 'Bihar',
    season: 'Annual',
    crop: 'Sugarcane',
    localName: 'गन्ना',
    primaryCategory: 'Commercial',
    sowingWindow: 'October (Autumn) & February–March (Spring)',
    growingWindow: 'April – September',
    harvestingWindow: 'November (Middle) – March (Late)',
    months: createMonthMap({
      sowing: { months: [10, 2, 3], timing: { 10: 'Middle', 2: 'Middle', 3: 'Middle' } },
      growing: { months: [4, 5, 6, 7, 8, 9] },
      harvesting: { months: [11, 12, 1], timing: { 11: 'Middle', 12: 'Middle', 1: 'Late' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'bih-moong',
    state: 'Bihar',
    season: 'Zaid / Summer',
    crop: 'Moong (Green Gram)',
    localName: 'मूंग',
    primaryCategory: 'Pulses',
    sowingWindow: 'March (Middle) – April (Early)',
    growingWindow: 'April – May',
    harvestingWindow: 'May (Late) – June (Middle)',
    months: createMonthMap({
      sowing: { months: [3, 4], timing: { 3: 'Middle to Late', 4: 'Early' } },
      growing: { months: [5] },
      harvesting: { months: [5, 6], timing: { 5: 'Late', 6: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'bih-jute',
    state: 'Bihar',
    season: 'Zaid / Summer',
    crop: 'Jute (Pat)',
    localName: 'जूट / पटसन',
    primaryCategory: 'Fibre',
    sowingWindow: 'March (Late) – May (Early)',
    growingWindow: 'May – June',
    harvestingWindow: 'July (Beginning) – August (Late)',
    months: createMonthMap({
      sowing: { months: [3, 4, 5], timing: { 3: 'Late', 4: 'Middle', 5: 'Early' } },
      growing: { months: [6] },
      harvesting: { months: [7, 8], timing: { 7: 'Beginning', 8: 'Late' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },

  // ==================== KARNATAKA ====================
  {
    id: 'kar-ragi',
    state: 'Karnataka',
    season: 'Kharif',
    crop: 'Ragi (Finger Millet)',
    localName: 'रागी (ರಾಗಿ)',
    primaryCategory: 'Foodgrain',
    sowingWindow: 'July (Early) – August (Late)',
    growingWindow: 'September – October',
    harvestingWindow: 'November (Beginning) – December (Late)',
    months: createMonthMap({
      sowing: { months: [7, 8], timing: { 7: 'Middle', 8: 'Middle' } },
      growing: { months: [9, 10] },
      harvesting: { months: [11, 12], timing: { 11: 'Beginning', 12: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'kar-cotton',
    state: 'Karnataka',
    season: 'Kharif',
    crop: 'Cotton',
    localName: 'कपास (ಹತ್ತಿ)',
    primaryCategory: 'Fibre',
    sowingWindow: 'June (Beginning) – July (Late)',
    growingWindow: 'August – October',
    harvestingWindow: 'November (Beginning) – January (Middle)',
    months: createMonthMap({
      sowing: { months: [6, 7], timing: { 6: 'Middle', 7: 'Middle' } },
      growing: { months: [8, 9, 10] },
      harvesting: { months: [11, 12, 1], timing: { 11: 'Beginning', 12: 'Middle', 1: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'kar-maize',
    state: 'Karnataka',
    season: 'Kharif',
    crop: 'Maize (Makka)',
    localName: 'मक्का (ಮೆಕ್ಕೆಜೋಳ)',
    primaryCategory: 'Foodgrain',
    sowingWindow: 'June (Early) – July (Late)',
    growingWindow: 'August',
    harvestingWindow: 'September (Late) – November (Beginning)',
    months: createMonthMap({
      sowing: { months: [6, 7], timing: { 6: 'Early to Middle', 7: 'Middle' } },
      growing: { months: [8] },
      harvesting: { months: [9, 10, 11], timing: { 9: 'Late', 10: 'Middle', 11: 'Beginning' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'kar-sugarcane',
    state: 'Karnataka',
    season: 'Annual',
    crop: 'Sugarcane',
    localName: 'गन्ना (ಕಬ್ಬು)',
    primaryCategory: 'Commercial',
    sowingWindow: 'January – March & July – August',
    growingWindow: 'April – October',
    harvestingWindow: 'November – April',
    months: createMonthMap({
      sowing: { months: [1, 2, 7, 8], timing: { 1: 'Middle', 2: 'Middle', 7: 'Middle', 8: 'Middle' } },
      growing: { months: [3, 4, 5, 6, 9, 10] },
      harvesting: { months: [11, 12], timing: { 11: 'Beginning', 12: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'kar-groundnut',
    state: 'Karnataka',
    season: 'Kharif',
    crop: 'Groundnut (Kadalekayi)',
    localName: 'मूंगफली (ಕಡಲೆಕಾಯಿ)',
    primaryCategory: 'Oilseeds',
    sowingWindow: 'June (Beginning) – July (Middle)',
    growingWindow: 'August – September',
    harvestingWindow: 'October (Beginning) – November (Early)',
    months: createMonthMap({
      sowing: { months: [6, 7], timing: { 6: 'Beginning to Middle', 7: 'Middle' } },
      growing: { months: [8, 9] },
      harvesting: { months: [10, 11], timing: { 10: 'Beginning', 11: 'Early' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'kar-tur',
    state: 'Karnataka',
    season: 'Kharif',
    crop: 'Tur / Red Gram (Togari)',
    localName: 'अरहर (ತೊಗರಿ)',
    primaryCategory: 'Pulses',
    sowingWindow: 'June (Late) – July (Late)',
    growingWindow: 'August – November',
    harvestingWindow: 'December (Middle) – January (Late)',
    months: createMonthMap({
      sowing: { months: [6, 7], timing: { 6: 'Late', 7: 'Middle' } },
      growing: { months: [8, 9, 10, 11] },
      harvesting: { months: [12, 1], timing: { 12: 'Middle', 1: 'Late' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'kar-gram',
    state: 'Karnataka',
    season: 'Rabi',
    crop: 'Bengal Gram (Kadale)',
    localName: 'चना (ಕಡಲೆ)',
    primaryCategory: 'Pulses',
    sowingWindow: 'October (Beginning) – November (Middle)',
    growingWindow: 'December – January',
    harvestingWindow: 'February (Middle) – March (Late)',
    months: createMonthMap({
      sowing: { months: [10, 11], timing: { 10: 'Beginning to Middle', 11: 'Early' } },
      growing: { months: [12, 1] },
      harvesting: { months: [2, 3], timing: { 2: 'Middle', 3: 'Late' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'kar-rice',
    state: 'Karnataka',
    season: 'Kharif',
    crop: 'Rice (Bhatta)',
    localName: 'धान (ಭತ್ತ)',
    primaryCategory: 'Foodgrain',
    sowingWindow: 'June (Middle) – July (Late)',
    growingWindow: 'August – October',
    harvestingWindow: 'November (Early) – December (Late)',
    months: createMonthMap({
      sowing: { months: [6, 7], timing: { 6: 'Middle', 7: 'Middle' } },
      growing: { months: [8, 9, 10] },
      harvesting: { months: [11, 12], timing: { 11: 'Early', 12: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'kar-sunflower',
    state: 'Karnataka',
    season: 'Kharif',
    crop: 'Sunflower',
    localName: 'सूरजमुखी (ಸೂರ್ಯಕಾಂತಿ)',
    primaryCategory: 'Oilseeds',
    sowingWindow: 'July (Beginning) – August (Late)',
    growingWindow: 'September',
    harvestingWindow: 'October (Middle) – November (Late)',
    months: createMonthMap({
      sowing: { months: [7, 8], timing: { 7: 'Middle', 8: 'Middle' } },
      growing: { months: [9] },
      harvesting: { months: [10, 11], timing: { 10: 'Middle', 11: 'Late' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },

  // ==================== TAMIL NADU ====================
  {
    id: 'tn-rice-samba',
    state: 'Tamil Nadu',
    season: 'Rabi',
    crop: 'Rice (Samba / Thaladi)',
    localName: 'धान (நெல்)',
    primaryCategory: 'Foodgrain',
    sowingWindow: 'August (Late) – October (Beginning)',
    growingWindow: 'October – December',
    harvestingWindow: 'January (Middle) – February (Late)',
    months: createMonthMap({
      sowing: { months: [8, 9, 10], timing: { 8: 'Late', 9: 'Middle', 10: 'Beginning' } },
      growing: { months: [11, 12] },
      harvesting: { months: [1, 2], timing: { 1: 'Middle', 2: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'tn-groundnut',
    state: 'Tamil Nadu',
    season: 'Kharif',
    crop: 'Groundnut',
    localName: 'मूंगफली (வேர்க்கடலை)',
    primaryCategory: 'Oilseeds',
    sowingWindow: 'June (Early) – July (Late)',
    growingWindow: 'August – September',
    harvestingWindow: 'October (Beginning) – November (Middle)',
    months: createMonthMap({
      sowing: { months: [6, 7], timing: { 6: 'Middle', 7: 'Middle' } },
      growing: { months: [8, 9] },
      harvesting: { months: [10, 11], timing: { 10: 'Beginning', 11: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'tn-sugarcane',
    state: 'Tamil Nadu',
    season: 'Annual',
    crop: 'Sugarcane (Karumbu)',
    localName: 'गन्ना (கரும்பு)',
    primaryCategory: 'Commercial',
    sowingWindow: 'December (Special) & January – March (Main)',
    growingWindow: 'April – October',
    harvestingWindow: 'November (Middle) – April (Late)',
    months: createMonthMap({
      sowing: { months: [12, 1, 2, 3], timing: { 12: 'Late', 1: 'Middle', 2: 'Middle', 3: 'Middle' } },
      growing: { months: [4, 5, 6, 7, 8, 9, 10] },
      harvesting: { months: [11, 12, 1], timing: { 11: 'Middle', 12: 'Middle', 1: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'tn-cotton',
    state: 'Tamil Nadu',
    season: 'Rabi',
    crop: 'Cotton (Paruthi)',
    localName: 'कपास (பருத்தி)',
    primaryCategory: 'Fibre',
    sowingWindow: 'August (Middle) – October (Beginning)',
    growingWindow: 'October – December',
    harvestingWindow: 'January (Middle) – March (Late)',
    months: createMonthMap({
      sowing: { months: [8, 9, 10], timing: { 8: 'Middle', 9: 'Middle', 10: 'Beginning' } },
      growing: { months: [11, 12] },
      harvesting: { months: [1, 2, 3], timing: { 1: 'Middle', 2: 'Middle', 3: 'Late' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'tn-maize',
    state: 'Tamil Nadu',
    season: 'Kharif',
    crop: 'Maize (Makkacholam)',
    localName: 'मक्का (மக்காச்சோளம்)',
    primaryCategory: 'Foodgrain',
    sowingWindow: 'July (Beginning) – August (Late)',
    growingWindow: 'September',
    harvestingWindow: 'October (Late) – December (Early)',
    months: createMonthMap({
      sowing: { months: [7, 8], timing: { 7: 'Middle', 8: 'Middle' } },
      growing: { months: [9] },
      harvesting: { months: [10, 11, 12], timing: { 10: 'Late', 11: 'Middle', 12: 'Early' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'tn-urad',
    state: 'Tamil Nadu',
    season: 'Rabi',
    crop: 'Black Gram (Ulundu)',
    localName: 'उड़द (உளுந்து)',
    primaryCategory: 'Pulses',
    sowingWindow: 'January (Beginning) – February (Middle)',
    growingWindow: 'March',
    harvestingWindow: 'April (Beginning) – May (Middle)',
    months: createMonthMap({
      sowing: { months: [1, 2], timing: { 1: 'Middle', 2: 'Early' } },
      growing: { months: [3] },
      harvesting: { months: [4, 5], timing: { 4: 'Beginning to Middle', 5: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'tn-moong',
    state: 'Tamil Nadu',
    season: 'Rabi',
    crop: 'Green Gram (Paasipanyaru)',
    localName: 'मूंग (பாசிப்பயறு)',
    primaryCategory: 'Pulses',
    sowingWindow: 'January (Beginning) – February (Middle)',
    growingWindow: 'March',
    harvestingWindow: 'April (Early) – May (Early)',
    months: createMonthMap({
      sowing: { months: [1, 2], timing: { 1: 'Middle', 2: 'Early' } },
      growing: { months: [3] },
      harvesting: { months: [4, 5], timing: { 4: 'Middle', 5: 'Early' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'tn-banana',
    state: 'Tamil Nadu',
    season: 'Annual',
    crop: 'Banana (Vazhai)',
    localName: 'केला (வாழை)',
    primaryCategory: 'Horticulture',
    sowingWindow: 'February – April & August – October',
    growingWindow: 'Year-round cultivation',
    harvestingWindow: '10–12 months after planting',
    months: createMonthMap({
      sowing: { months: [2, 3, 8, 9], timing: { 2: 'Middle', 3: 'Middle', 8: 'Middle', 9: 'Middle' } },
      growing: { months: [4, 5, 6, 7, 10, 11] },
      harvesting: { months: [12, 1], timing: { 12: 'Middle', 1: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },

  // ==================== ANDHRA PRADESH ====================
  {
    id: 'ap-rice',
    state: 'Andhra Pradesh',
    season: 'Kharif',
    crop: 'Rice (Paddy)',
    localName: 'धान (వరి)',
    primaryCategory: 'Foodgrain',
    sowingWindow: 'June (Late) – July (Late)',
    growingWindow: 'August – October',
    harvestingWindow: 'November (Early) – December (Late)',
    months: createMonthMap({
      sowing: { months: [6, 7], timing: { 6: 'Late', 7: 'Middle' } },
      growing: { months: [8, 9, 10] },
      harvesting: { months: [11, 12], timing: { 11: 'Early', 12: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'ap-chillies',
    state: 'Andhra Pradesh',
    season: 'Kharif',
    crop: 'Chillies (Mirchi)',
    localName: 'मिर्च (మిరప)',
    primaryCategory: 'Commercial',
    sowingWindow: 'July (Middle) – August (Late)',
    growingWindow: 'September – November',
    harvestingWindow: 'December (Middle) – March (Late)',
    months: createMonthMap({
      sowing: { months: [7, 8], timing: { 7: 'Middle', 8: 'Late' } },
      growing: { months: [9, 10, 11] },
      harvesting: { months: [12, 1, 2, 3], timing: { 12: 'Middle', 1: 'Middle', 2: 'Middle', 3: 'Late' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'ap-cotton',
    state: 'Andhra Pradesh',
    season: 'Kharif',
    crop: 'Cotton (Patti)',
    localName: 'कपास (పత్తి)',
    primaryCategory: 'Fibre',
    sowingWindow: 'June (Middle) – July (Late)',
    growingWindow: 'August – October',
    harvestingWindow: 'November (Middle) – January (Late)',
    months: createMonthMap({
      sowing: { months: [6, 7], timing: { 6: 'Middle to Late', 7: 'Middle' } },
      growing: { months: [8, 9, 10] },
      harvesting: { months: [11, 12, 1], timing: { 11: 'Middle', 12: 'Middle', 1: 'Late' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'ap-maize',
    state: 'Andhra Pradesh',
    season: 'Kharif',
    crop: 'Maize (Mokkajnna)',
    localName: 'मक्का (మొక్కజొన్న)',
    primaryCategory: 'Foodgrain',
    sowingWindow: 'June (Late) – July (Late)',
    growingWindow: 'August',
    harvestingWindow: 'September (Late) – October (Late)',
    months: createMonthMap({
      sowing: { months: [6, 7], timing: { 6: 'Late', 7: 'Middle' } },
      growing: { months: [8] },
      harvesting: { months: [9, 10], timing: { 9: 'Late', 10: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'ap-groundnut',
    state: 'Andhra Pradesh',
    season: 'Kharif',
    crop: 'Groundnut (Verusanaga)',
    localName: 'मूंगफली (వేరుశనగ)',
    primaryCategory: 'Oilseeds',
    sowingWindow: 'June (Middle) – July (Late)',
    growingWindow: 'August – September',
    harvestingWindow: 'October (Beginning) – November (Middle)',
    months: createMonthMap({
      sowing: { months: [6, 7], timing: { 6: 'Middle', 7: 'Middle' } },
      growing: { months: [8, 9] },
      harvesting: { months: [10, 11], timing: { 10: 'Beginning', 11: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'ap-tur',
    state: 'Andhra Pradesh',
    season: 'Kharif',
    crop: 'Red Gram / Tur (Kandi)',
    localName: 'अरहर (కంది)',
    primaryCategory: 'Pulses',
    sowingWindow: 'June (Late) – July (Late)',
    growingWindow: 'August – November',
    harvestingWindow: 'December (Late) – January (Late)',
    months: createMonthMap({
      sowing: { months: [6, 7], timing: { 6: 'Late', 7: 'Middle' } },
      growing: { months: [8, 9, 10, 11] },
      harvesting: { months: [12, 1], timing: { 12: 'Late', 1: 'Late' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'ap-gram',
    state: 'Andhra Pradesh',
    season: 'Rabi',
    crop: 'Bengal Gram (Sanaga)',
    localName: 'चना (శనగ)',
    primaryCategory: 'Pulses',
    sowingWindow: 'October (Middle) – November (Late)',
    growingWindow: 'December – January',
    harvestingWindow: 'February (Late) – March (Middle)',
    months: createMonthMap({
      sowing: { months: [10, 11], timing: { 10: 'Middle to Late', 11: 'Middle' } },
      growing: { months: [12, 1] },
      harvesting: { months: [2, 3], timing: { 2: 'Late', 3: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'ap-sugarcane',
    state: 'Andhra Pradesh',
    season: 'Annual',
    crop: 'Sugarcane (Cheraku)',
    localName: 'गन्ना (చెరకు)',
    primaryCategory: 'Commercial',
    sowingWindow: 'January – March',
    growingWindow: 'April – October',
    harvestingWindow: 'December – April',
    months: createMonthMap({
      sowing: { months: [1, 2, 3], timing: { 1: 'Middle', 2: 'Middle', 3: 'Middle' } },
      growing: { months: [4, 5, 6, 7, 8, 9, 10] },
      harvesting: { months: [12, 1, 2], timing: { 12: 'Middle', 1: 'Middle', 2: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },

  // ==================== WEST BENGAL ====================
  {
    id: 'wb-rice-aman',
    state: 'West Bengal',
    season: 'Kharif',
    crop: 'Rice (Aman)',
    localName: 'धान (ধান)',
    primaryCategory: 'Foodgrain',
    sowingWindow: 'June (Middle) – July (Late)',
    growingWindow: 'August – October',
    harvestingWindow: 'November (Middle) – December (Late)',
    months: createMonthMap({
      sowing: { months: [6, 7], timing: { 6: 'Middle', 7: 'Late' } },
      growing: { months: [8, 9, 10] },
      harvesting: { months: [11, 12], timing: { 11: 'Middle', 12: 'Late' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'wb-jute',
    state: 'West Bengal',
    season: 'Zaid / Summer',
    crop: 'Jute (Pat)',
    localName: 'जूट / पटसन (পাট)',
    primaryCategory: 'Fibre',
    sowingWindow: 'March (Late) – May (Middle)',
    growingWindow: 'May – June',
    harvestingWindow: 'July (Beginning) – August (Late)',
    months: createMonthMap({
      sowing: { months: [3, 4, 5], timing: { 3: 'Late', 4: 'Middle', 5: 'Middle' } },
      growing: { months: [6] },
      harvesting: { months: [7, 8], timing: { 7: 'Beginning', 8: 'Late' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'wb-potato',
    state: 'West Bengal',
    season: 'Rabi',
    crop: 'Potato (Aloo)',
    localName: 'आलू (আলু)',
    primaryCategory: 'Horticulture',
    sowingWindow: 'November (Beginning) – December (Middle)',
    growingWindow: 'January',
    harvestingWindow: 'February (Middle) – March (Late)',
    months: createMonthMap({
      sowing: { months: [11, 12], timing: { 11: 'Middle', 12: 'Middle' } },
      growing: { months: [1] },
      harvesting: { months: [2, 3], timing: { 2: 'Middle', 3: 'Late' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'wb-mustard',
    state: 'West Bengal',
    season: 'Rabi',
    crop: 'Mustard / Rai (Sorshe)',
    localName: 'सरसों (সর্ষে)',
    primaryCategory: 'Oilseeds',
    sowingWindow: 'October (Late) – November (Late)',
    growingWindow: 'December – January',
    harvestingWindow: 'February (Middle) – March (Middle)',
    months: createMonthMap({
      sowing: { months: [10, 11], timing: { 10: 'Late', 11: 'Middle' } },
      growing: { months: [12, 1] },
      harvesting: { months: [2, 3], timing: { 2: 'Middle', 3: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'wb-wheat',
    state: 'West Bengal',
    season: 'Rabi',
    crop: 'Wheat (Gom)',
    localName: 'गेहूं (গম)',
    primaryCategory: 'Foodgrain',
    sowingWindow: 'November (Middle) – December (Early)',
    growingWindow: 'January – February',
    harvestingWindow: 'March (Middle) – April (Beginning)',
    months: createMonthMap({
      sowing: { months: [11, 12], timing: { 11: 'Middle to Late', 12: 'Early' } },
      growing: { months: [1, 2] },
      harvesting: { months: [3, 4], timing: { 3: 'Middle', 4: 'Beginning' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'wb-maize',
    state: 'West Bengal',
    season: 'Rabi',
    crop: 'Maize (Bhutta)',
    localName: 'मक्का (ভুট্টা)',
    primaryCategory: 'Foodgrain',
    sowingWindow: 'October (Late) – November (Late)',
    growingWindow: 'December – February',
    harvestingWindow: 'March (Late) – April (Late)',
    months: createMonthMap({
      sowing: { months: [10, 11], timing: { 10: 'Late', 11: 'Middle' } },
      growing: { months: [12, 1, 2] },
      harvesting: { months: [3, 4], timing: { 3: 'Late', 4: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'wb-masoor',
    state: 'West Bengal',
    season: 'Rabi',
    crop: 'Lentil (Mosur Dal)',
    localName: 'मसूर (মসুর ডাল)',
    primaryCategory: 'Pulses',
    sowingWindow: 'October (Late) – November (Late)',
    growingWindow: 'December – January',
    harvestingWindow: 'February (Late) – March (Late)',
    months: createMonthMap({
      sowing: { months: [10, 11], timing: { 10: 'Late', 11: 'Middle' } },
      growing: { months: [12, 1] },
      harvesting: { months: [2, 3], timing: { 2: 'Late', 3: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },

  // ==================== ALL INDIA (NATIONAL REFERENCE) ====================
  {
    id: 'nat-wheat',
    state: 'All India',
    season: 'Rabi',
    crop: 'Wheat',
    localName: 'गेहूं',
    primaryCategory: 'Foodgrain',
    sowingWindow: 'October (Late) – December (Early)',
    growingWindow: 'January – February',
    harvestingWindow: 'March (Middle) – April (Late)',
    months: createMonthMap({
      sowing: { months: [10, 11, 12], timing: { 10: 'Late', 11: 'Middle', 12: 'Early' } },
      growing: { months: [1, 2] },
      harvesting: { months: [3, 4], timing: { 3: 'Middle', 4: 'Late' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'nat-rice',
    state: 'All India',
    season: 'Kharif',
    crop: 'Rice (Paddy)',
    localName: 'धान',
    primaryCategory: 'Foodgrain',
    sowingWindow: 'June (Beginning) – July (Late)',
    growingWindow: 'August – September',
    harvestingWindow: 'October (Beginning) – November (Late)',
    months: createMonthMap({
      sowing: { months: [6, 7], timing: { 6: 'Middle', 7: 'Middle' } },
      growing: { months: [8, 9] },
      harvesting: { months: [10, 11], timing: { 10: 'Middle', 11: 'Late' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'nat-mustard',
    state: 'All India',
    season: 'Rabi',
    crop: 'Mustard & Rapeseed',
    localName: 'सरसों',
    primaryCategory: 'Oilseeds',
    sowingWindow: 'September (Late) – November (Early)',
    growingWindow: 'December – January',
    harvestingWindow: 'February (Middle) – March (Late)',
    months: createMonthMap({
      sowing: { months: [9, 10, 11], timing: { 9: 'Late', 10: 'Middle', 11: 'Early' } },
      growing: { months: [12, 1] },
      harvesting: { months: [2, 3], timing: { 2: 'Middle', 3: 'Late' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'nat-gram',
    state: 'All India',
    season: 'Rabi',
    crop: 'Gram (Chana)',
    localName: 'चना',
    primaryCategory: 'Pulses',
    sowingWindow: 'October (Beginning) – November (Middle)',
    growingWindow: 'December – January',
    harvestingWindow: 'February (Late) – March (Late)',
    months: createMonthMap({
      sowing: { months: [10, 11], timing: { 10: 'Middle', 11: 'Early' } },
      growing: { months: [12, 1] },
      harvesting: { months: [2, 3], timing: { 2: 'Late', 3: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'nat-cotton',
    state: 'All India',
    season: 'Kharif',
    crop: 'Cotton',
    localName: 'कपास',
    primaryCategory: 'Fibre',
    sowingWindow: 'May (Beginning) – July (Late)',
    growingWindow: 'August – October',
    harvestingWindow: 'October (Late) – January (Late)',
    months: createMonthMap({
      sowing: { months: [5, 6, 7], timing: { 5: 'Middle', 6: 'Middle', 7: 'Middle' } },
      growing: { months: [8, 9, 10] },
      harvesting: { months: [11, 12, 1], timing: { 11: 'Middle', 12: 'Middle', 1: 'Late' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'nat-sugarcane',
    state: 'All India',
    season: 'Annual',
    crop: 'Sugarcane',
    localName: 'गन्ना',
    primaryCategory: 'Commercial',
    sowingWindow: 'October (Autumn) & February–March (Spring)',
    growingWindow: 'April – October',
    harvestingWindow: 'November (Middle) – April (Late)',
    months: createMonthMap({
      sowing: { months: [10, 2, 3], timing: { 10: 'Middle', 2: 'Middle', 3: 'Middle' } },
      growing: { months: [4, 5, 6, 7, 8, 9] },
      harvesting: { months: [11, 12, 1], timing: { 11: 'Middle', 12: 'Middle', 1: 'Late' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'nat-maize',
    state: 'All India',
    season: 'Kharif',
    crop: 'Maize (Corn)',
    localName: 'मक्का',
    primaryCategory: 'Foodgrain',
    sowingWindow: 'June (Middle) – July (Late)',
    growingWindow: 'August',
    harvestingWindow: 'September (Late) – November (Beginning)',
    months: createMonthMap({
      sowing: { months: [6, 7], timing: { 6: 'Late', 7: 'Middle' } },
      growing: { months: [8] },
      harvesting: { months: [9, 10, 11], timing: { 9: 'Late', 10: 'Middle', 11: 'Beginning' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'nat-soybean',
    state: 'All India',
    season: 'Kharif',
    crop: 'Soybean',
    localName: 'सोयाबीन',
    primaryCategory: 'Oilseeds',
    sowingWindow: 'June (Middle) – July (Middle)',
    growingWindow: 'August',
    harvestingWindow: 'September (Late) – October (Late)',
    months: createMonthMap({
      sowing: { months: [6, 7], timing: { 6: 'Late', 7: 'Middle' } },
      growing: { months: [8] },
      harvesting: { months: [9, 10], timing: { 9: 'Late', 10: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'nat-bajra',
    state: 'All India',
    season: 'Kharif',
    crop: 'Bajra (Pearl Millet)',
    localName: 'बाजरा',
    primaryCategory: 'Foodgrain',
    sowingWindow: 'June (Late) – July (Late)',
    growingWindow: 'August',
    harvestingWindow: 'September (Middle) – October (Late)',
    months: createMonthMap({
      sowing: { months: [6, 7], timing: { 6: 'Late', 7: 'Middle' } },
      growing: { months: [8] },
      harvesting: { months: [9, 10], timing: { 9: 'Middle', 10: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'nat-jowar',
    state: 'All India',
    season: 'Kharif',
    crop: 'Jowar (Sorghum)',
    localName: 'ज्वार',
    primaryCategory: 'Foodgrain',
    sowingWindow: 'June (Late) – July (Middle)',
    growingWindow: 'August – September',
    harvestingWindow: 'October (Beginning) – November (Middle)',
    months: createMonthMap({
      sowing: { months: [6, 7], timing: { 6: 'Late', 7: 'Middle' } },
      growing: { months: [8, 9] },
      harvesting: { months: [10, 11], timing: { 10: 'Beginning', 11: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'nat-groundnut',
    state: 'All India',
    season: 'Kharif',
    crop: 'Groundnut (Peanut)',
    localName: 'मूंगफली',
    primaryCategory: 'Oilseeds',
    sowingWindow: 'June (Middle) – July (Middle)',
    growingWindow: 'August – September',
    harvestingWindow: 'October (Beginning) – November (Middle)',
    months: createMonthMap({
      sowing: { months: [6, 7], timing: { 6: 'Middle', 7: 'Middle' } },
      growing: { months: [8, 9] },
      harvesting: { months: [10, 11], timing: { 10: 'Beginning', 11: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'nat-tur',
    state: 'All India',
    season: 'Kharif',
    crop: 'Tur / Arhar (Pigeon Pea)',
    localName: 'अरहर',
    primaryCategory: 'Pulses',
    sowingWindow: 'June (Middle) – July (Middle)',
    growingWindow: 'August – November',
    harvestingWindow: 'December (Middle) – January (Late)',
    months: createMonthMap({
      sowing: { months: [6, 7], timing: { 6: 'Middle to Late', 7: 'Middle' } },
      growing: { months: [8, 9, 10, 11] },
      harvesting: { months: [12, 1], timing: { 12: 'Middle', 1: 'Late' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'nat-potato',
    state: 'All India',
    season: 'Rabi',
    crop: 'Potato',
    localName: 'आलू',
    primaryCategory: 'Horticulture',
    sowingWindow: 'October (Beginning) – November (Late)',
    growingWindow: 'December',
    harvestingWindow: 'January (Late) – March (Middle)',
    months: createMonthMap({
      sowing: { months: [10, 11], timing: { 10: 'Middle', 11: 'Middle' } },
      growing: { months: [12] },
      harvesting: { months: [1, 2, 3], timing: { 1: 'Late', 2: 'Middle', 3: 'Early' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'nat-onion',
    state: 'All India',
    season: 'Rabi',
    crop: 'Onion',
    localName: 'प्याज',
    primaryCategory: 'Horticulture',
    sowingWindow: 'October (Middle) – December (Late)',
    growingWindow: 'January – February',
    harvestingWindow: 'March (Late) – May (Middle)',
    months: createMonthMap({
      sowing: { months: [10, 11, 12], timing: { 10: 'Middle', 11: 'Middle', 12: 'Middle' } },
      growing: { months: [1, 2] },
      harvesting: { months: [3, 4, 5], timing: { 3: 'Late', 4: 'Middle', 5: 'Early' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'nat-moong',
    state: 'All India',
    season: 'Zaid / Summer',
    crop: 'Moong (Green Gram)',
    localName: 'मूंग',
    primaryCategory: 'Pulses',
    sowingWindow: 'March (Middle) – April (Middle)',
    growingWindow: 'April – May',
    harvestingWindow: 'May (Late) – June (Middle)',
    months: createMonthMap({
      sowing: { months: [3, 4], timing: { 3: 'Middle', 4: 'Early' } },
      growing: { months: [5] },
      harvesting: { months: [5, 6], timing: { 5: 'Late', 6: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
  {
    id: 'nat-urad',
    state: 'All India',
    season: 'Kharif',
    crop: 'Urad (Black Gram)',
    localName: 'उड़द',
    primaryCategory: 'Pulses',
    sowingWindow: 'June (Late) – July (Late)',
    growingWindow: 'August',
    harvestingWindow: 'September (Late) – October (Late)',
    months: createMonthMap({
      sowing: { months: [6, 7], timing: { 6: 'Late', 7: 'Middle' } },
      growing: { months: [8] },
      harvesting: { months: [9, 10], timing: { 9: 'Late', 10: 'Middle' } },
    }),
    source: 'UPAg / ICAR & Indian Horticulture Database - 2014',
  },
];
